In [12]:
import pandas as pd

df = pd.read_csv("../data/raw/twcs.csv")

In [ ]:
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nFirst 5 rows:")
print(df.head())

print("\nDataset information:")
df.info()

print("\nStatistical summary:")
print(df.describe())

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:")
print(df.duplicated().sum())

print("\nUnique values in inbound:")
print(df["inbound"].unique())

print("\nCount of each inbound value:")
print(df["inbound"].value_counts())

Shape: (2811774, 7)

Columns:
Index(['tweet_id', 'author_id', 'inbound', 'created_at', 'text',
       'response_tweet_id', 'in_response_to_tweet_id'],
      dtype='object')

First 5 rows:
   tweet_id   author_id  inbound                      created_at  \
0         1  sprintcare    False  Tue Oct 31 22:10:47 +0000 2017
1         2      115712     True  Tue Oct 31 22:11:45 +0000 2017
2         3      115712     True  Tue Oct 31 22:08:27 +0000 2017
3         4  sprintcare    False  Tue Oct 31 21:54:49 +0000 2017
4         5      115712     True  Tue Oct 31 21:49:35 +0000 2017

                                                text response_tweet_id  \
0  @115712 I understand. I would like to assist y...                 2
1      @sprintcare and how do you propose we do that               NaN
2  @sprintcare I have sent several private messag...                 1
3  @115712 Please send us a Private Message so th...                 3
4                                 @sprintcare I did.                 4

   in_response_to_tweet_id
0                      3.0
1                      1.0
2                      4.0
3                      5.0
4                      6.0

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2811774 entries, 0 to 2811773
Data columns (total 7 columns):
 #   Column                   Dtype
---  ------                   -----
 0   tweet_id                 int64
 1   author_id                object
 2   inbound                  bool
 3   created_at               object
 4   text                     object
 5   response_tweet_id        object
 6   in_response_to_tweet_id  float64
dtypes: bool(1), float64(1), int64(1), object(4)
memory usage: 131.4+ MB

Statistical summary:
           tweet_id  in_response_to_tweet_id
count  2.811774e+06             2.017439e+06
mean   1.504565e+06             1.463141e+06
std    8.616450e+05             8.665730e+05
min    1.000000e+00             1.000000e+00
25%    7.601652e+05             7.155105e+05
50%    1.507772e+06             1.439805e+06
75%    2.253296e+06             2.220646e+06
max    2.987950e+06             2.987950e+06
Missing values:
tweet_id                         0
author_id                        0
inbound                          0
created_at                       0
text                             0
response_tweet_id          1040629
in_response_to_tweet_id     794335
dtype: int64

Duplicate rows:
0

Unique values in inbound:
[False  True]

Count of each inbound value:
inbound
True     1537843
False    1273931
Name: count, dtype: int64

In [19]:
# Calculate author-level statistics

author_stats = df.groupby("author_id").agg(
    inbound_tweets=("inbound", "sum"),
    total_tweets=("tweet_id", "count")
)

author_stats["outbound_tweets"] = (
    author_stats["total_tweets"] -
    author_stats["inbound_tweets"]
)

author_stats = author_stats[
    ["inbound_tweets", "outbound_tweets", "total_tweets"]
]

print("\nAuthor-level statistics:")
print(author_stats.head())

# Authors with at least one outbound tweet
authors_with_outbound = author_stats[
    author_stats["outbound_tweets"] > 0
]

print("\nAuthors with at least one outbound tweet:")
print(authors_with_outbound.shape)

# Top authors by outbound tweet count
top_outbound = authors_with_outbound.sort_values(
    "outbound_tweets",
    ascending=False
)

print(top_outbound.head(20))

Author-level statistics:
           inbound_tweets  outbound_tweets  total_tweets
author_id
10026                   3                0             3
100363                  1                0             1
10103                   2                0             2
10221                   2                0             2
10286                   1                0             1

Authors with at least one outbound tweet:
(108, 3)
                 inbound_tweets  outbound_tweets  total_tweets
author_id
AmazonHelp                    0           169840        169840
AppleSupport                  0           106860        106860
Uber_Support                  0            56270         56270
SpotifyCares                  0            43265         43265
Delta                         0            42253         42253
Tesco                         0            38573         38573
AmericanAir                   0            36764         36764
TMobileHelp                   0            34317         34317
comcastcares                  0            33031         33031
British_Airways               0            29361         29361
SouthwestAir                  0            28977         28977
VirginTrains                  0            27817         27817
Ask_Spectrum                  0            25860         25860
XboxSupport                   0            24557         24557
sprintcare                    0            22381         22381
hulu_support                  0            21872         21872
sainsburys                    0            19466         19466
GWRHelp                       0            19364         19364
AskPlayStation                0            19098         19098
ChipotleTweets                0            18749         18749

In [20]:
# Select only outbound tweets
outbound = df[df["inbound"] == False]

# Connect each outbound tweet to the tweet it is responding to
outbound_customer = outbound.merge(
    df[["tweet_id", "author_id"]],
    left_on="in_response_to_tweet_id",
    right_on="tweet_id",
    suffixes=("_brand", "_customer")
)

# Count distinct customers for each brand
customer_counts = (
    outbound_customer
    .groupby("author_id_brand")["author_id_customer"]
    .nunique()
    .reset_index(name="distinct_customers")
)

# Sort by number of customers
customer_counts = customer_counts.sort_values(
    "distinct_customers",
    ascending=False
)

# Display top authors
customer_counts.head(20)

     author_id_brand  distinct_customers
10      AppleSupport               76366
8         AmazonHelp               71049
85      Uber_Support               38300
77      SpotifyCares               27794
40             Delta               22331
99      comcastcares               21824
9        AmericanAir               21686
78       TMobileHelp               19943
76      SouthwestAir               19713
26      Ask_Spectrum               17214
80             Tesco               15594
83           UPSHelp               14616
37    ChipotleTweets               14374
33   British_Airways               14213
100     hulu_support               13462
92       XboxSupport               13150
107       sprintcare               12896
90      VirginTrains               12631
1         ATVIAssist               12423
19    AskPlayStation               12214

In [ ]:
# Select AppleSupport's outbound tweets
apple_outbound = df[
    (df["author_id"] == "AppleSupport") &
    (df["inbound"] == False)
]

# Get the customer tweet IDs that AppleSupport responded to
apple_customer_tweets = apple_outbound[
    "in_response_to_tweet_id"
].dropna()

# Count unique customer tweets
number_of_conversations = apple_customer_tweets.nunique()

print("Number of conversation threads involving AppleSupport:",
      number_of_conversations)

Number of conversation threads involving AppleSupport: 106696

In [23]:
# Convert parent tweet ID to numeric

df["in_response_to_tweet_id"] = pd.to_numeric(
    df["in_response_to_tweet_id"],
    errors="coerce"
).astype("Int64")

# Create mapping:
#    tweet_id → tweet id is replying to

parent = dict(
    zip(
        df["tweet_id"],
        df["in_response_to_tweet_id"]
    )
)

# Function to find the original/root tweet

def find_root(tweet_id):
    visited = set()

    while pd.notna(parent.get(tweet_id)):

        # Prevent infinite loops
        if tweet_id in visited:
            break

        visited.add(tweet_id)

        tweet_id = int(parent[tweet_id])

    return tweet_id

# Assign conversation ID to every tweet

df["conversation_id"] = df["tweet_id"].map(find_root)

# Define the 5 brands

brands = [
    "AppleSupport",
    "AmazonHelp",
    "Uber_Support",
    "SpotifyCares",
    "Delta"
]

# Calculate conversation statistics

results = []

for brand in brands:

    # Tweets posted by this brand
    brand_tweets = df[
        df["author_id"] == brand
    ]

    # Conversation IDs involving this brand
    conversation_ids = brand_tweets[
        "conversation_id"
    ].unique()

    # Get all tweets belonging to those conversations
    conversations = df[
        df["conversation_id"].isin(conversation_ids)
    ]

    # Number of complete conversation threads
    number_of_conversations = (
        conversations["conversation_id"].nunique()
    )

    # Number of customer messages
    number_of_customer_messages = (
        conversations["inbound"] == True
    ).sum()

    # Number of brand responses
    number_of_brand_responses = (
        (conversations["author_id"] == brand) &
        (conversations["inbound"] == False)
    ).sum()

    # Store results
    results.append({
        "Brand": brand,
        "Number of conversations": number_of_conversations,
        "Number of customer messages": number_of_customer_messages,
        "Number of brand responses": number_of_brand_responses
    })


conversation_summary = pd.DataFrame(results)

print(conversation_summary)

          Brand  Number of conversations  Number of customer messages  \
0  AppleSupport                    80702                       131764
1    AmazonHelp                    82534                       203598
2  Uber_Support                    41923                        72154
3  SpotifyCares                    28280                        48543
4         Delta                    26166                        45296

   Number of brand responses
0                     106860
1                     169840
2                      56270
3                      43265
4                      42253

In [32]:
# ============================================================
# Validate reconstructed AppleSupport conversations
# ============================================================

# 1. Get all conversation IDs involving AppleSupport
apple_conversation_ids = df[
    df["author_id"] == "AppleSupport"
]["conversation_id"].dropna().unique()


# 2. Select 5 conversation IDs
sample_conversations = pd.Series(
    apple_conversation_ids
).sample(30, random_state=42)


# 3. Display each conversation
for conversation_id in sample_conversations:

    print("=" * 100)
    print(f"Conversation: {conversation_id}")
    print("=" * 100)

    # Get all tweets belonging to this conversation
    conversation = df[
        df["conversation_id"] == conversation_id
    ].copy()

    # Sort chronologically
    conversation = conversation.sort_values("created_at")

    # Display required columns
    print(
        conversation[
            [
                "conversation_id",
                "tweet_id",
                "created_at",
                "author_id",
                "inbound",
                "text"
            ]
        ].to_string(index=False)
    )

    print("\n")

====================================================================================================
Conversation: 1216340
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                                           text
         1216340   1216340 Wed Oct 25 17:02:51 +0000 2017       405412     True                                   @AppleSupport hi, my gifs are sending extremely small to others but I receive their gifs at normal size. How can I fix this?
         1216340   1216338 Wed Oct 25 17:21:29 +0000 2017 AppleSupport    False                                                @405412 We're happy to take a look in to this with you and figure out what is going on! What device is this on?
         1216340   1216339 Wed Oct 25 17:23:26 +0000 2017       405412     True @AppleSupport Thank you! It’s on an iPhone7 Plus running on iOS 11.0.3. So far I’ve restarted my phone &amp; also toggled iMessage on and off but no luck. Lol
         1216340   1216342 Wed Oct 25 17:33:50 +0000 2017       405412     True                                            @AppleSupport This is how small they’re appearing when I send them. The size of the bubble. https://t.co/073zgjzmC6
         1216340   1216341 Wed Oct 25 17:42:58 +0000 2017 AppleSupport    False                                                                                 @405412 Does this only occur with iMessage, or does it occur with SMS as well?
         1216340   1216343 Wed Oct 25 17:46:43 +0000 2017       405412     True                                                                                                                                   @AppleSupport Only iMessage.
         1216340   1216344 Wed Oct 25 18:01:06 +0000 2017 AppleSupport    False                                                         @405412 Meet us in DM, then we can dig in to this further with you from there. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 2278476
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                     text
         2278476   2278476 Sat Nov 11 14:26:18 +0000 2017       662493     True This update only made my battery worst it didn’t fix the I problem @AppleSupport https://t.co/ghILmO7T5A
         2278476   2278475 Sat Nov 11 18:46:53 +0000 2017 AppleSupport    False  @662493 Let's look into that. Send us a direct message and we'll go from there. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 1196358
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                   text
         1196358   1196358 Wed Oct 25 02:23:45 +0000 2017       272912     True Charging my phone for the fifth time today! I love bringing my external battery with me...like a tamagotchi for adults! Thanks,@115858
         1196358   1196357 Wed Oct 25 02:31:34 +0000 2017 AppleSupport    False               @272912 Let's look into this for you. How long does full charge usually last? Let us know in DM. https://t.co/GDrqU2kzhr


====================================================================================================
Conversation: 849905
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                   text
          849905    849905 Fri Oct 20 13:15:26 +0000 2017       321943     True                                Is there no night mode in iOS 11.0.3? I loved it 😒@115858 @AppleSupport
          849905    849904 Fri Oct 20 15:11:01 +0000 2017 AppleSupport    False @321943 We're here for you. Find instructions for turning on Night Shift here: https://t.co/NBE76DOiEM


====================================================================================================
Conversation: 32376
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                               text
           32376     32376 Wed Nov 01 06:05:03 +0000 2017       123173     True       Oye @115858, muy bonitos tus nuevos emojis pero, ¿para cuando el poder desactivar (REAL) el Wifi y el Bluetooth desde el CC?
           32376     32375 Wed Nov 01 12:55:00 +0000 2017 AppleSupport    False @123173 We offer support via Twitter in English. Get help in Spanish here: https://t.co/IBIY3vMgPj or join https://t.co/OczyRx7IOs


====================================================================================================
Conversation: 2971310
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                text
         2971310   2971310 Thu Nov 30 00:48:19 +0000 2017       819571     True                    Dawg this iPhone X front camera on Snapchat is fucking garbage ya'll shit looks like an iPhone 4
         2971310   2971309 Thu Nov 30 00:49:01 +0000 2017       819571     True                                                                                      @AppleSupport explain this fam
         2971310   2971308 Thu Nov 30 00:57:29 +0000 2017 AppleSupport    False @819571 Send us a DM. Let us know more details about this issue. We'll do our best to help. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 1774679
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                                   text
         1774679   1774679 Wed Nov 08 03:11:14 +0000 2017       533325     True @AppleSupport On top of that my daughter’s brand new 8 plus - bought two days ago - crashed and won’t even turn on. What is happening with your brand?
         1774679   1774678 Wed Nov 08 04:41:51 +0000 2017 AppleSupport    False                          @533325 We're here to help get this sorted out for you. DM us and we'll see what we can do to assist. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 2896081
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                                                 text
         2896081   2896081 Tue Nov 28 16:35:26 +0000 2017       802515     True                                                                 having major bug issues w/ the @318 app running 11.1.2. I use this app daily. 💀@AppleSupport @115858
         2896081   2896080 Tue Nov 28 16:42:00 +0000 2017 AppleSupport    False @802515 We're glad you took the time to reach out. We can definitely look into this with you. Can you tell us what's happening specifically? https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 1605529
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                                     text
         1605529   1605529 Sat Nov 04 16:10:53 +0000 2017       492503     True                                             Yo @115858 when are you going to fix these hieroglyph blocks I keep texting in since I've updated my phone??
         1605529   1605527 Sat Nov 04 22:22:25 +0000 2017       492502     True                                                                                       @492503 @115858 I just got the 8 &amp; the shit keeps doing it too
         1605529   1605528 Sat Nov 04 22:39:21 +0000 2017       492503     True @492502 @115858 it's hella embarrassing when I send a text message and half the letters are blocks 😂 I have to explain the update to everyone right away
         1605529   1605526 Sun Nov 05 02:23:51 +0000 2017 AppleSupport    False               @492502  Please check out this resource. If you type the letter “i” &amp; it autocorrects to an “A” with a symbol: https://t.co/xXaXeeSRt9
         1605529   1606743 Sun Nov 05 02:37:00 +0000 2017 AppleSupport    False                                    @492503  Let's help. Try this out: https://t.co/uSEvRC9KDv us know if that helps correct that issue with autocorrect.


====================================================================================================
Conversation: 1527771
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                               text
         1527771   1527771 Fri Nov 03 17:48:21 +0000 2017       474365     True                           @115858 your updates are trash and my phone is glitching
         1527771   1527770 Fri Nov 03 22:16:25 +0000 2017 AppleSupport    False @474365 Please let us know more about what you're experiencing. We'd love to help.


====================================================================================================
Conversation: 538637
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                 text
          538637    538637 Sat Dec 02 04:57:56 +0000 2017       244878     True                                   Hey, @AppleSupport @115858 - y’all up? A word about this date thing would be nice.
          538637    538636 Sat Dec 02 14:42:32 +0000 2017 AppleSupport    False @244878 We are here to help. DM us the details of your issue and we can take a look at this. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 2014188
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                                   text
         2014188   2014188 Sun Nov 05 10:12:07 +0000 2017       595578     True                                Now this tweet look stupid as hell. Is this your way of forcing me to buy the iPhone X? @115858 https://t.co/X2Xon9vHvF
         2014188   2014187 Sun Nov 05 17:32:26 +0000 2017 AppleSupport    False @595578 Thanks for reaching out. We have a workaround for this here: https://t.co/xXaXeeSRt9 and DM us if you still need help. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 1750453
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                          text
         1750453   1750453 Tue Nov 07 16:05:25 +0000 2017       475766     True                                                                          I️ hope @115858 can fix this question mark disaster.
         1750453   1750452 Tue Nov 07 18:02:00 +0000 2017 AppleSupport    False @475766 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/xXaXeeSRt9


====================================================================================================
Conversation: 1386416
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                               text
         1386416   1386416 Mon Oct 16 15:05:56 +0000 2017       209634     True @AppleSupport  Another iOS bug. Even though I have camera toggled to JPG it keeps switching to taking HEIC format - Please fix it.
         1386416   1386415 Mon Oct 16 15:23:01 +0000 2017 AppleSupport    False                @209634 We'd be happy to review this for you. Are you experiencing this issue on the latest version of iOS, 11.0.3?


====================================================================================================
Conversation: 658304
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                               text
          658304    658304 Thu Oct 05 09:29:07 +0000 2017       276725     True                                                                        De verdad @AppleSupport @115858 ??? https://t.co/hsHMlbzGgr
          658304    658303 Thu Oct 05 14:12:00 +0000 2017 AppleSupport    False @276725 We offer support via Twitter in English. Get help in Spanish here: https://t.co/IBIY3vMgPj or join https://t.co/OczyRx7IOs


====================================================================================================
Conversation: 2948223
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                      text
         2948223   2948223 Wed Nov 29 16:20:12 +0000 2017       814247     True                 What’s the best way to wash the sport loop for Apple Watch? @AppleSupport
         2948223   2948222 Wed Nov 29 16:39:01 +0000 2017 AppleSupport    False @814247 This guide will help you get that taken care of properly: https://t.co/VxlvpoL1kr


====================================================================================================
Conversation: 1134158
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                                        text
         1134158   1134157 Sun Oct 29 07:26:43 +0000 2017       252840     True  @AppleSupport Yup, definitely sucks. Half the reason for using pull-up screen is Bluetooth toggle. If you want to accommodate watch, make it a sub-setting
         1134158   1134158 Tue Oct 24 05:20:54 +0000 2017       252840     True                @115858, your last 2+ iOS updates feature a disconnect between turning Bluetooth off from swipe up screen and the on/off switch in settings.
         1134158   1134155 Tue Oct 24 12:46:28 +0000 2017 AppleSupport    False                                                                           @252840 This is intended. You can read more on that here: https://t.co/G7BHuQnDS6
         1134158   1134156 Tue Oct 24 13:34:08 +0000 2017       252840     True @AppleSupport Not good. Pain in the rear just to accommodate other-device connections? You guys keep doing stuff to push me away from @115858 (prev: jack).


====================================================================================================
Conversation: 2067908
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                                           text
         2067908   2067908 Sun Oct 08 06:52:56 +0000 2017       611521     True                    I had a ton of space left on my phone when I synched it yesterday but suddenly it's full? Excuse me? @AppleSupport Explain.
         2067908   2067907 Sun Oct 08 14:40:28 +0000 2017 AppleSupport    False @611521 How much space is available on your iPhone? Let us know in DM and we'll work together to get this figured out. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 1531327
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                text
         1531327   1531327 Fri Nov 03 15:27:06 +0000 2017       475062     True                             @115858 i updated my phone &amp; still see boxes this is unacceptable🤬🤬
         1531327   1531326 Fri Nov 03 20:21:33 +0000 2017 AppleSupport    False @475062 We'd love to help. DM us what country or region your're located in. https://t.co/GDrqU22YpT


====================================================================================================
Conversation: 682019
====================================================================================================
 conversation_id  tweet_id                     created_at    author_id  inbound                                                                                                                          text
          682019    682019 Wed Nov 08 00:53:30 +0000 2017       282761     True                                                                                 @115858 can you PUH lease fix these I️t boxes
          682019    682018 Wed Nov 08 04:07:25 +0000 2017 AppleSupport    False @282761 Here’s what you can do to work around the issue until it’s fixed in a future software update: https://t.co/qODbOsp4wz
          682019    682017 Wed Nov 08 04:10:34 +0000 2017       282761     True                                                                                           @AppleSupport I’ll see if I️t works

In [26]:
conversation_summary["Average messages per conversation"] = (
    conversation_summary["Number of customer messages"]
    + conversation_summary["Number of brand responses"]
) / conversation_summary["Number of conversations"]

conversation_summary

,Brand,Number of conversations,Number of customer messages,Number of brand responses,Average messages per conversation
0,AppleSupport,80702,131764,106860,2.956854
1,AmazonHelp,82534,203598,169840,4.524657
2,Uber_Support,41923,72154,56270,3.063330
3,SpotifyCares,28280,48543,43265,3.246393
4,Delta,26166,45296,42253,3.345907

In [31]:
# ============================================================
# Validate reconstructed AmazonHelp conversations
# ============================================================

# 1. Get all conversation IDs involving AmazonHelp
amazon_conversation_ids = df[
    df["author_id"] == "AmazonHelp"
]["conversation_id"].dropna().unique()


# 2. Select 5 conversation IDs
sample_conversations = pd.Series(
    amazon_conversation_ids
).sample(30, random_state=42)


# 3. Display each conversation
for conversation_id in sample_conversations:

    print("=" * 100)
    print(f"Conversation: {conversation_id}")
    print("=" * 100)

    # Get all tweets belonging to this conversation
    conversation = df[
        df["conversation_id"] == conversation_id
    ].copy()

    # Sort chronologically
    conversation = conversation.sort_values("created_at")

    # Display required columns
    print(
        conversation[
            [
                "conversation_id",
                "tweet_id",
                "created_at",
                "author_id",
                "inbound",
                "text"
            ]
        ].to_string(index=False)
    )

    print("\n")

====================================================================================================
Conversation: 2116198
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                    text
         2116198   2116198 Wed Nov 08 13:33:51 +0000 2017     623804     True                   amazonミュージック普段あんまり使ってないけど、ペルソナのサントラが聞き放題だときいてみてみたらほんとに凄い数あってびっくりした\n永遠にBGMにこまらないやつだ……
         2116198   2116197 Wed Nov 08 13:43:30 +0000 2017 AmazonHelp    False @623804 Amazon Musicをご利用いただき、ありがとうございます！いろいろなジャンルの曲を取り揃えておりますので、どうぞ存分にお楽しみください♪ (エンドレスで…)O o｡.(´-`*) RI


====================================================================================================
Conversation: 1402844
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                         text
         1402844   1402844 Sat Oct 28 17:43:26 +0000 2017     446166     True                       Thanks @115821 for messing up my order just because I deleted an item that hadn't even shipped yet. Very disappointed.
         1402844   1402843 Sat Oct 28 17:46:00 +0000 2017 AmazonHelp    False       @446166 I'm sorry to hear about that, Jeanette. W/o personal or account info, could you tell us a little more about what happened? ^BL
         1402844   1402842 Sat Oct 28 17:57:21 +0000 2017     446166     True @AmazonHelp when I canceled one of my items because size was not shown up front it pushed my entire order back and I had to cancel all of it
         1402844   1402840 Sat Oct 28 18:00:01 +0000 2017 AmazonHelp    False                         @446166 I apologize for the frustration that has caused. Did you receive a new delivery date when this happened? ^BA
         1402844   1402841 Sat Oct 28 18:01:31 +0000 2017     446166     True                                                                                                         @AmazonHelp I did very disappointing


====================================================================================================
Conversation: 2918648
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                                                                             text
         2918648   2918648 Wed Nov 29 00:29:40 +0000 2017     807839     True                                                                                                                                                MEUS LIVROS CHEGARAM HOJE AAAAAAAA TE AMO @115821
         2918648   2918647 Wed Nov 29 00:33:35 +0000 2017 AmazonHelp    False                                                                    @807839 Uhuuuu! Que felicidade bia! Nós também te amamos! Fala pra gente, o que você comrpou? 😍🎁👏 ^JJ https://t.co/U6wBM0sgaA
         2918648   2918643 Wed Nov 29 00:35:29 +0000 2017     807839     True                                                                                                              @AmazonHelp miga comprei 5 livros e ó veio tudo certinho aaaaaaaaaaaa pisa menos 💞💞
         2918648   2918641 Wed Nov 29 00:39:00 +0000 2017 AmazonHelp    False                                                                                                                   @807839 Que livros bia? Eu sou fã dos livros românticos e do suspense! ❤️💙 ^JJ
         2918648   2918642 Wed Nov 29 00:42:58 +0000 2017     807839     True                                                  @AmazonHelp esses aqui, amo suspense e amo o harlan coben so faz hino de livros sjnsbsksbskssksns vc ja leu algum dele? https://t.co/0NO1yS2pB6
         2918648   2918644 Wed Nov 29 00:46:25 +0000 2017 AmazonHelp    False @807839 Que lindoooooo! Uma amiga acabou de ler Tartarugas até lá embaixo e me falou que é maravilhoso! Qual deles você vai ler de primeiro bia? Deixa eu adivinhar! Tartarugas? Rs rs rs 😍🐢 ^JJ
         2918648   2918645 Wed Nov 29 00:49:37 +0000 2017     807839     True                                                                                                           @AmazonHelp hahahahahahahha opa temos uma vidente aqui produçao, vai ser esse mesmo 💞💃
         2918648   2918646 Wed Nov 29 00:53:32 +0000 2017 AmazonHelp    False                                                                                                  @807839 Rs! Boa escolha, Bia! Espero que você curta muito a leitura do livro! 📚✨ Abraço! :3 ^CR


====================================================================================================
Conversation: 1245953
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                       text
         1245953   1245953 Thu Oct 26 00:13:24 +0000 2017     412292     True                                                                 @AmazonHelp Hey still can't access my account anyone home?
         1245953   1245952 Thu Oct 26 00:31:32 +0000 2017 AmazonHelp    False @412292 Oh no! Just to confirm, the entire website is not loading for you? Or are you not able to log in? Let us know! ^SA


====================================================================================================
Conversation: 1657876
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                                                    text
         1657876   1657876 Mon Nov 06 03:52:59 +0000 2017     505840     True @115821 @AmazonHelp Why such a big box for #amazon 2 items? I ❤️my delivered items, but this huge box &amp; extra bubbles, waste of resources.🤔 https://t.co/psMsMrfJLp
         1657876   1657875 Mon Nov 06 04:18:52 +0000 2017 AmazonHelp    False                                           @505840 Thank you for reaching out to us! Please provide packaging feedback for improvement here: https://t.co/brHaIDcirk ^NN


====================================================================================================
Conversation: 2205142
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                          text
         2205142   2205142 Thu Nov 09 23:35:45 +0000 2017     644769     True Shit I forgot to cancel my Amazon student free trial, so its just taken money out of my account to pay for a whole year of Prime...FUCKKKKKKK
         2205142   2205143 Thu Nov 09 23:38:42 +0000 2017 AmazonHelp    False       @644769 Sorry for the unexpected charge! You can cancel here: https://t.co/A6f5nzpzdt if you don't wish to continue the membership. ^EZ
         2205142   2205141 Thu Nov 09 23:39:30 +0000 2017 AmazonHelp    False                                                      @644769 So sorry, please use this link: https://t.co/vr5I3Rg5un or UK Prime account. ^EZ


====================================================================================================
Conversation: 294304
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                  text
          294304    294304 Fri Oct 06 17:30:08 +0000 2017     186085     True @115825 Kann man schon sagen, wann #Grimm Staffel 6 in deutsch über #AmazonPrime verfügbar sein wird?
          294304    294303 Fri Oct 06 17:41:15 +0000 2017 AmazonHelp    False                                     @186085 Leider nein 🙁 Bleib uns treu, und du verpasst Nichts. ^DW


====================================================================================================
Conversation: 245942
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                 text
          245942    245942 Thu Oct 05 15:11:52 +0000 2017     174411     True                           *Pays for a prime membership just to get shipping dates that are 10 days out* ....I'm mad at y'all @115821
          245942    245941 Thu Oct 05 15:14:28 +0000 2017 AmazonHelp    False @174411 Our Prime shipping refers to the transit time after the item ships. Have we missed a delivery date provided at checkout? ^GR


====================================================================================================
Conversation: 1254125
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                     text
         1254125   1254124 Thu Oct 26 06:25:00 +0000 2017 AmazonHelp    False                          @414082 Ich versteh deine Verärgerung absolut. 😕 Daher kontaktiere bitte unseren Kundenservice zur Klärung. ^TG
         1254125   1254123 Thu Oct 26 06:27:59 +0000 2017     414082     True @AmazonHelp Bringt das was? Wenn die Ware wohl anscheinend nichtmal da ist? 🙁 Ich hab euch voll gern, hasse es, sauer auf "euch" zu sein
         1254125   1254122 Thu Oct 26 06:31:45 +0000 2017 AmazonHelp    False    @414082 Mrs. Winchester wir haben dich mindestens genauso gerne und würden gerne helfen, zumindest eine Erklärung zu finden. Gruß ^DW
         1254125   1254121 Thu Oct 26 06:36:10 +0000 2017     414082     True             @AmazonHelp Ich guck mal, ob ich eurem Telefonservice nochmal ne Chance gebe 🙈 Die sind net immer so freundlich wie ihr hier
         1254125   1254120 Thu Oct 26 06:39:29 +0000 2017 AmazonHelp    False                                                           @414082 Davon gehe ich jetzt mal aus. Aber wenn was ist, melde dich bitte. ^TG
         1254125   1254119 Thu Oct 26 06:40:41 +0000 2017     414082     True      @AmazonHelp Mach ich. Vielen Dank schon mal für die Hilfe. Wünsche einen angenehmen Arbeitstag und nen schönen Feierabend später! 😊
         1254125   1254118 Thu Oct 26 06:43:01 +0000 2017 AmazonHelp    False                                                  @414082 Gerne und auch danke. Hab ebenso einen wundervollen Tag! Ganz liebe Grüße 😍 ^TG


====================================================================================================
Conversation: 21459
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                        text
           21459     21459 Wed Nov 01 07:14:42 +0000 2017     120689     True           Friend has received his Amazon Echo Plus shipment in the morning today. Still waiting for my dot.
           21459     21457 Wed Nov 01 07:54:26 +0000 2017 AmazonHelp    False                        @120689 Could you please confirm if we have missed the mentioned time frame? 2/2 ^AH
           21459     21460 Wed Nov 01 07:54:26 +0000 2017 AmazonHelp    False @120689 Our products are shipped on time so that they can reach you by the estimated delivery date. 1/2 ^AH
           21459     21458 Wed Nov 01 08:03:26 +0000 2017     120689     True                                                      @AmazonHelp Not at all, you’re on schedule. Thanks. :)


====================================================================================================
Conversation: 1119289
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                text
         1119289   1119289 Sun Oct 15 12:35:44 +0000 2017     384095     True                                      Amazonからのお支払い番号お知らせメールってメールじゃなくてメッセージでもくるの？私メアド持ってない…\nそしてそれは注文してからしばらく待たないとこないの？\n不安しかないんだけど…
         1119289   1119287 Sun Oct 15 12:49:29 +0000 2017 AmazonHelp    False                       @384095 リプライ失礼いたします。携帯電話番号でアカウントをご登録されておりますか？その場合、Eメールはお送りできませんので、アカウントサービス内の「メッセージセンター」にて注文に関する案内をご確認ください。HM
         1119289   1119288 Sun Oct 15 13:34:16 +0000 2017     384095     True                                                          @AmazonHelp わざわざすいません！！えっと、Amazon確認コードはメールじゃなくてメッセージで来たので携帯電話番号で登録したと思います！
         1119289   1119290 Sun Oct 15 13:41:30 +0000 2017 AmazonHelp    False @384095 左様でございましたか。お支払い番号は、Ｅメールにてお送りします。そのため、アドレス登録がない場合は、メッセージセンターでご確認ください。メッセージセンターは、以下リンクからもアクセスできます。　https://t.co/qxvc47GM40 SM
         1119289   1119291 Sun Oct 15 16:06:00 +0000 2017     384095     True                                                                      @AmazonHelp ありがとうございました！友人にきいたら詳しく教えてくれ、無事にお支払い番号お知らせメールがきました！
         1119289   1119292 Sun Oct 15 22:39:27 +0000 2017 AmazonHelp    False                                                                                  @384095 確認ができたとのことで安心いたしました。今後ともどうぞよろしくお願いいたします。SK


====================================================================================================
Conversation: 2805922
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                          text
         2805922   2805922 Wed Nov 22 02:40:49 +0000 2017     341644     True                                            Thankeew @115850 for solving my problem, good behaviour by customer care executive
         2805922   2805921 Wed Nov 22 03:10:00 +0000 2017 AmazonHelp    False @341644 You are most welcome! We are glad to know that your problem is solved. Do keep us posted on any further concerns. ^SC


====================================================================================================
Conversation: 467382
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                                                                                          text
          467382    467382 Fri Dec 01 05:25:14 +0000 2017     226257     True @116316 ach mit euch hab ich oft genug Probleme jetzt ist mein Problem dass ich mein gekauftes Album (JBG3) nicht über Amazon Music runterladen kann und das schon seit 00:00 obwohl heute release ist Danke!
          467382    467380 Fri Dec 01 05:36:27 +0000 2017 AmazonHelp    False                                                                                                                                                    @226257 Erscheint es in deiner Musikbibiliothek? Grüße ^TG
          467382    467378 Fri Dec 01 05:46:32 +0000 2017     226257     True                                                                                                                                                                                 @AmazonHelp Nein ist es nicht
          467382    467381 Fri Dec 01 05:47:30 +0000 2017     226257     True                                                                                                                                                                          @AmazonHelp  https://t.co/3BaFRNqstl
          467382    467376 Fri Dec 01 05:51:29 +0000 2017 AmazonHelp    False                                                                             @226257 Melde dich mal im Kundenservice. Die Kollegen finden heraus, was da nicht stimmt: https://t.co/5RHhEVutwe Viele Grüße ^UK
          467382    467377 Fri Dec 01 05:51:57 +0000 2017     226257     True                                                                                                                                                                                          @AmazonHelp Ok danke
          467382    467379 Sat Dec 02 05:54:30 +0000 2017 AmazonHelp    False                                                                                                       @226257 Hey, wir wollten kurz mal nachfragen, ob dir die Kollegen vom Kundenservice helfen konnten? ^MS
          467382    467476 Sat Dec 02 10:35:07 +0000 2017     226257     True                                                                                                                                                                         @AmazonHelp Ja sie haben mir geholfen
          467382    467477 Sat Dec 02 10:57:00 +0000 2017 AmazonHelp    False                                                                                                                                        @226257 Ok super. Dann wünsch ich dir noch ein schönes Wochenende. ^MS


====================================================================================================
Conversation: 1267601
====================================================================================================
 conversation_id  tweet_id                     created_at  author_id  inbound                                                                                                                                                       text
         1267601   1267601 Thu Oct 26 13:16:05 +0000 2017     126446     True                                  @AmazonHelp please teach your chat reps to actually read the question that's being asked not just...making up a question?
         1267601   1267599 Thu Oct 26 13:21:00 +0000 2017 AmazonHelp    False                                                      @126446 Hello, I am sorry to hear this. Has the question been answered or can we be of any help ? ^CR
         1267601   1267600 Thu Oct 26 13:22:42 +0000 2017     126446     True @AmazonHelp its been fixed now &amp; i left feedback but it would help if your chat reps would read the question carefully before responding. had to state
         1267601   1267602 Thu Oct 26 13:23:08 +0000 2017     126446     True                                    @AmazonHelp it three different times before they understood what i was saying. and i didn't change the question at all.
         1267601   1267603 Thu Oct 26 13:32:01 +0000 2017 AmazonHelp    False             @126446 I'm sorry for the inconvenience. The survey at the end allows you to leave feedback for the agent, &amp; goes to their supervisor. ^LB