In [1]:
import pandas as pd

amazon_df = pd.read_csv(
    "../data/processed/amazonhelp_cleaned.csv"
)

print("Shape:", amazon_df.shape)

number_of_conversations = amazon_df["conversation_id"].nunique()

print("Number of conversations:", number_of_conversations)

conversation_lengths = (
    amazon_df
    .groupby("conversation_id")
    .size()
    .rename("conversation_length")
)

print(conversation_lengths.describe())

length_distribution = conversation_lengths.value_counts().sort_index()

print(length_distribution)

length_groups = pd.cut(
    conversation_lengths,
    bins=[0, 1, 2, 3, 4, float("inf")],
    labels=["1 turn", "2 turns", "3 turns", "4 turns", "5+ turns"]
)

length_summary = length_groups.value_counts().sort_index()

print(length_summary)

length_percentage = (
    length_summary
    / length_summary.sum()
    * 100
)

length_distribution_table = pd.DataFrame({
    "conversations": length_summary,
    "percentage": length_percentage.round(2)
})

print(length_distribution_table)

amazonhelp_conversations = (
    amazon_df[
        amazon_df["author_id"] == "AmazonHelp"
    ]["conversation_id"]
    .nunique()
)

print(
    "Conversations containing AmazonHelp responses:",
    amazonhelp_conversations
)

amazonhelp_percentage = (
    amazonhelp_conversations
    / number_of_conversations
    * 100
)

print(
    "Percentage:",
    round(amazonhelp_percentage, 2),
    "%"
)

message_roles = amazon_df["inbound"].value_counts()

print(message_roles)

customer_messages = (
    amazon_df["inbound"] == True
).sum()

amazonhelp_messages = (
    amazon_df["inbound"] == False
).sum()

print("Customer messages:", customer_messages)
print("AmazonHelp responses:", amazonhelp_messages)

conversation_role_summary = (
    amazon_df
    .groupby("conversation_id")
    .agg(
        total_messages=("tweet_id", "count"),
        customer_messages=("inbound", "sum")
    )
)

conversation_role_summary["amazonhelp_responses"] = (
    conversation_role_summary["total_messages"]
    - conversation_role_summary["customer_messages"]
)

conversation_role_summary.head()

two_sided_conversations = conversation_role_summary[
    (conversation_role_summary["customer_messages"] > 0) &
    (conversation_role_summary["amazonhelp_responses"] > 0)
]

print(
    "Two-sided conversations:",
    len(two_sided_conversations)
)

two_sided_percentage = (
    len(two_sided_conversations)
    / number_of_conversations
    * 100
)

print(
    "Percentage of two-sided conversations:",
    round(two_sided_percentage, 2),
    "%"
)

Shape: (374026, 10)
Number of conversations: 82534
count    82534.000000
mean         4.531781
std          5.321938
min          1.000000
25%          2.000000
50%          3.000000
75%          5.000000
max        448.000000
Name: conversation_length, dtype: float64
conversation_length
1          1
2      31292
3      11570
4      14014
5       6063
       ...
161        1
207        1
218        1
425        1
448        2
Name: count, Length: 99, dtype: int64
conversation_length
1 turn          1
2 turns     31292
3 turns     11570
4 turns     14014
5+ turns    25657
Name: count, dtype: int64
                     conversations  percentage
conversation_length
1 turn                           1        0.00
2 turns                      31292       37.91
3 turns                      11570       14.02
4 turns                      14014       16.98
5+ turns                     25657       31.09
Conversations containing AmazonHelp responses: 82534
Percentage: 100.0 %
inbound
True     203582
False    170444
Name: count, dtype: int64
Customer messages: 203582
AmazonHelp responses: 170444
Two-sided conversations: 82533
Percentage of two-sided conversations: 100.0 %

In [2]:
import re

intent_keywords = {

    # --------------------------------------------------------
    # 4.1 Delivery
    # --------------------------------------------------------
    "DELIVERY_DELAY": [
        "late delivery",
        "delivery delayed",
        "delivery delay",
        "delayed delivery",
        "arriving late",
        "arrived late"
    ],

    "DELIVERY_NOT_RECEIVED": [
        "not received",
        "didn't receive",
        "did not receive",
        "haven't received",
        "have not received",
        "never received",
        "package hasn't arrived",
        "package has not arrived"
    ],

    "DELIVERED_BUT_MISSING": [
        "marked delivered",
        "shows delivered",
        "says delivered",
        "delivered but",
        "delivered and missing",
        "says it was delivered"
    ],

    "DELIVERY_LOCATION_PROBLEM": [
        "wrong address",
        "wrong location",
        "wrong place",
        "delivered to neighbor",
        "delivered to neighbour",
        "delivery location",
        "delivery instructions"
    ],

    "COURIER_OR_DRIVER_ISSUE": [
        "delivery driver",
        "driver",
        "courier",
        "delivery person",
        "delivery guy",
        "driver was",
        "courier was"
    ],

    "DELIVERY_TRACKING_PROBLEM": [
        "tracking",
        "tracking number",
        "tracking hasn't updated",
        "tracking has not updated",
        "tracking not updating",
        "tracking information"
    ],

    "DELIVERY_ATTEMPT_PROBLEM": [
        "delivery attempt",
        "attempted delivery",
        "delivery attempted",
        "couldn't deliver",
        "could not deliver",
        "delivery failed"
    ],

    "DAMAGED_DURING_DELIVERY": [
        "damaged during delivery",
        "damaged package",
        "package damaged",
        "arrived damaged",
        "box damaged",
        "package was damaged"
    ],


    # --------------------------------------------------------
    # 4.2 Orders
    # --------------------------------------------------------
    "ORDER_CANCELLATION": [
        "cancel my order",
        "cancel order",
        "order cancellation",
        "cancelled my order",
        "canceled my order"
    ],

    "ORDER_PLACEMENT_PROBLEM": [
        "can't place order",
        "cannot place order",
        "unable to place order",
        "can't order",
        "cannot order",
        "place my order",
        "place an order"
    ],

    "ORDER_STATUS": [
        "order status",
        "where is my order",
        "order update",
        "order hasn't arrived",
        "order has not arrived",
        "check my order"
    ],

    "ORDER_MODIFICATION": [
        "change my order",
        "modify my order",
        "change order",
        "modify order",
        "edit my order"
    ],

    "WRONG_OR_MISSING_ITEM": [
        "wrong item",
        "wrong product",
        "missing item",
        "item missing",
        "missing product",
        "received the wrong"
    ],

    "PRODUCT_AVAILABILITY": [
        "out of stock",
        "out-of-stock",
        "not available",
        "product availability",
        "when will it be available",
        "back in stock"
    ],


    # --------------------------------------------------------
    # 4.3 Returns & Refunds
    # --------------------------------------------------------
    "RETURN_REQUEST": [
        "return this",
        "return my",
        "return an item",
        "want to return",
        "want a return",
        "return request"
    ],

    "RETURN_ELIGIBILITY": [
        "eligible for return",
        "return eligible",
        "can I return",
        "can i return",
        "return eligibility",
        "eligible to return"
    ],

    "RETURN_PICKUP_PROBLEM": [
        "return pickup",
        "return pick up",
        "pickup didn't happen",
        "pickup did not happen",
        "pickup hasn't happened",
        "courier didn't pick up",
        "courier did not pick up"
    ],

    "RETURN_PROBLEM": [
        "return problem",
        "return issue",
        "problem with my return",
        "issue with my return",
        "return isn't working",
        "return is not working"
    ],

    "REFUND_PROBLEM": [
        "refund",
        "refund problem",
        "refund issue",
        "refund hasn't arrived",
        "refund has not arrived",
        "refund not received",
        "where is my refund"
    ],

    "REPLACEMENT_PROBLEM": [
        "replacement",
        "replacement problem",
        "replacement issue",
        "replacement hasn't arrived",
        "replacement has not arrived",
        "replace my item"
    ],


    # --------------------------------------------------------
    # 4.4 Payment & Billing
    # --------------------------------------------------------
    "PAYMENT_FAILURE": [
        "payment failed",
        "payment failure",
        "payment declined",
        "payment was declined",
        "can't make payment",
        "cannot make payment"
    ],

    "CHARGE_PROBLEM": [
        "charged",
        "charge problem",
        "wrong charge",
        "unexpected charge",
        "incorrect charge",
        "charged me"
    ],

    "DUPLICATE_CHARGE": [
        "charged twice",
        "charged two times",
        "double charge",
        "duplicate charge",
        "charged me twice"
    ],

    "UNAUTHORIZED_PAYMENT": [
        "unauthorized payment",
        "unauthorized charge",
        "payment I didn't make",
        "payment i did not make",
        "charge I didn't make",
        "charge i did not make"
    ],

    "AMAZON_PAY_PROBLEM": [
        "amazon pay",
        "amazonpay",
        "amazon pay problem",
        "amazon pay issue"
    ],


    # --------------------------------------------------------
    # 4.5 Prime & Subscriptions
    # --------------------------------------------------------
    "PRIME_MEMBERSHIP_PROBLEM": [
        "prime membership",
        "prime membership problem",
        "prime membership issue",
        "prime member"
    ],

    "PRIME_CHARGE_OR_RENEWAL": [
        "prime charge",
        "prime charged",
        "prime renewal",
        "prime renewed",
        "prime renewal charge",
        "charged for prime"
    ],

    "PRIME_BENEFIT_PROBLEM": [
        "prime benefit",
        "prime benefits",
        "prime benefit not working",
        "prime benefits not working",
        "prime isn't working",
        "prime is not working"
    ],

    "SUBSCRIPTION_PROBLEM": [
        "subscription",
        "subscription problem",
        "subscription issue",
        "cancel subscription",
        "subscription charge",
        "subscription renewed"
    ],


    # --------------------------------------------------------
    # 4.6 Technical / Digital
    # --------------------------------------------------------
    "DEVICE_PROBLEM": [
        "echo",
        "alexa",
        "kindle",
        "fire tv",
        "device problem",
        "device issue",
        "device isn't working",
        "device is not working"
    ],

    "APP_OR_WEBSITE_PROBLEM": [
        "amazon app",
        "app problem",
        "app issue",
        "website problem",
        "website issue",
        "website isn't working",
        "website is not working"
    ],

    "DIGITAL_CONTENT_PROBLEM": [
        "digital content",
        "ebook",
        "e-book",
        "kindle book",
        "digital book",
        "digital purchase"
    ],

    "STREAMING_OR_PLAYBACK_PROBLEM": [
        "streaming",
        "playback",
        "video not playing",
        "music not playing",
        "video playback",
        "can't watch",
        "cannot watch"
    ],

    "ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM": [
        "connect",
        "connection problem",
        "connectivity",
        "connected",
        "link my account",
        "account linking",
        "linking account"
    ],


    # --------------------------------------------------------
    # 4.7 Security & Fraud
    # --------------------------------------------------------
    "SUSPICIOUS_EMAIL_OR_PHISHING": [
        "phishing",
        "suspicious email",
        "suspicious e-mail",
        "fake email",
        "fake e-mail",
        "is this email from amazon",
        "is this a real email"
    ],

    "SCAM_OR_FRAUD_CONCERN": [
        "scam",
        "fraud",
        "fraudulent",
        "scammed",
        "scammer",
        "fraud concern"
    ],

    "UNAUTHORIZED_ACCOUNT_ACTIVITY": [
        "unauthorized account",
        "someone accessed my account",
        "account hacked",
        "account was hacked",
        "someone logged into my account",
        "someone has access to my account"
    ],


    # --------------------------------------------------------
    # 4.8 Promotions & Offers
    # --------------------------------------------------------
    "PROMOTION_OR_DISCOUNT_PROBLEM": [
        "promotion",
        "promotional",
        "discount",
        "promo code",
        "promo",
        "discount code"
    ],

    "CASHBACK_PROBLEM": [
        "cashback",
        "cash back",
        "cashback missing",
        "cashback not received"
    ],

    "CONTEST_OR_QUIZ_INQUIRY": [
        "contest",
        "quiz",
        "contest winner",
        "quiz winner",
        "contest result",
        "quiz result"
    ],

    "OFFER_ELIGIBILITY": [
        "offer eligibility",
        "eligible for this offer",
        "eligible for the offer",
        "qualify for the offer",
        "qualify for this promotion"
    ],


    # --------------------------------------------------------
    # 4.9 Customer Service
    # --------------------------------------------------------
    "CUSTOMER_SERVICE_COMPLAINT": [
        "customer service",
        "customer support",
        "support was",
        "support team",
        "bad customer service",
        "poor customer service"
    ],

    "SUPPORT_AGENT_COMPLAINT": [
        "agent",
        "support agent",
        "customer service agent",
        "agent was rude",
        "rude agent",
        "agent didn't help",
        "agent did not help"
    ],

    "UNRESOLVED_SUPPORT_ISSUE": [
        "not resolved",
        "still not resolved",
        "issue isn't resolved",
        "issue is not resolved",
        "problem still exists",
        "still having this problem",
        "no solution"
    ],

    "ESCALATION_REQUEST": [
        "escalate",
        "escalation",
        "escalate this",
        "speak to a manager",
        "talk to a manager",
        "supervisor"
    ],


    # --------------------------------------------------------
    # 4.10 General / Other
    # --------------------------------------------------------
    "GENERAL_INFORMATION": [
        "information",
        "question",
        "how does",
        "how do I",
        "how can I"
    ],

    "PRODUCT_INFORMATION": [
        "product information",
        "product details",
        "product question",
        "tell me about this product",
        "does this product"
    ],

    "FEEDBACK": [
        "feedback",
        "suggestion",
        "suggest",
        "recommendation"
    ],

    "APPRECIATION": [
        "thank you amazon",
        "thanks amazon",
        "thank you",
        "thanks",
        "great service",
        "excellent service"
    ],

    "UNCLEAR_REQUEST": []
}


# ============================================================
# Find candidate conversations for each intent
# ============================================================

family_candidates = {}

for intent, keywords in intent_keywords.items():

    # If no keywords are defined
    if not keywords:
        family_candidates[intent] = pd.Series(
            dtype="object"
        )
        continue

    # Escape keywords so special regex characters
    # do not cause problems
    escaped_keywords = [
        re.escape(keyword)
        for keyword in keywords
    ]

    pattern = "|".join(escaped_keywords)

    mask = (
        amazon_df["clean_text"]
        .fillna("")
        .str.contains(
            pattern,
            case=False,
            regex=True,
            na=False
        )
    )

    family_candidates[intent] = (
        amazon_df.loc[mask, "conversation_id"]
        .dropna()
        .drop_duplicates()
    )


# ============================================================
# Display candidate counts
# ============================================================

sampling_summary = pd.DataFrame({
    "intent": list(family_candidates.keys()),
    "candidate_conversations": [
        len(family_candidates[intent])
        for intent in family_candidates
    ]
})

sampling_summary = sampling_summary.sort_values(
    "candidate_conversations",
    ascending=False
)

print(sampling_summary.to_string(index=False))

                                 intent  candidate_conversations
                           APPRECIATION                    16111
                    GENERAL_INFORMATION                    13867
             CUSTOMER_SERVICE_COMPLAINT                    10458
                               FEEDBACK                     6440
                         REFUND_PROBLEM                     5842
              DELIVERY_TRACKING_PROBLEM                     4822
                         DEVICE_PROBLEM                     4686
                COURIER_OR_DRIVER_ISSUE                     4571
                  DELIVERY_NOT_RECEIVED                     4047
ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM                     3121
               PRIME_MEMBERSHIP_PROBLEM                     2523
                    REPLACEMENT_PROBLEM                     1983
                     ESCALATION_REQUEST                     1976
          PROMOTION_OR_DISCOUNT_PROBLEM                     1405
                         CHARGE_PROBLEM                     1383
                SUPPORT_AGENT_COMPLAINT                     1318
                  SCAM_OR_FRAUD_CONCERN                     1286
                   PRODUCT_AVAILABILITY                      978
                     AMAZON_PAY_PROBLEM                      869
                  DELIVERED_BUT_MISSING                      834
                           ORDER_STATUS                      803
                       CASHBACK_PROBLEM                      750
                   SUBSCRIPTION_PROBLEM                      703
               DELIVERY_ATTEMPT_PROBLEM                      679
                  WRONG_OR_MISSING_ITEM                      580
                CONTEST_OR_QUIZ_INQUIRY                      547
                DIGITAL_CONTENT_PROBLEM                      539
                         RETURN_REQUEST                      531
                     ORDER_CANCELLATION                      517
              DELIVERY_LOCATION_PROBLEM                      463
                         DELIVERY_DELAY                      434
               UNRESOLVED_SUPPORT_ISSUE                      385
          STREAMING_OR_PLAYBACK_PROBLEM                      357
                 APP_OR_WEBSITE_PROBLEM                      334
                ORDER_PLACEMENT_PROBLEM                      255
                DAMAGED_DURING_DELIVERY                      213
                  RETURN_PICKUP_PROBLEM                      163
           SUSPICIOUS_EMAIL_OR_PHISHING                      152
                       DUPLICATE_CHARGE                      132
                PRIME_CHARGE_OR_RENEWAL                       85
                     RETURN_ELIGIBILITY                       83
                  PRIME_BENEFIT_PROBLEM                       81
                    PRODUCT_INFORMATION                       75
          UNAUTHORIZED_ACCOUNT_ACTIVITY                       65
                        PAYMENT_FAILURE                       55
                         RETURN_PROBLEM                       24
                     ORDER_MODIFICATION                       16
                   UNAUTHORIZED_PAYMENT                        7
                      OFFER_ELIGIBILITY                        5
                        UNCLEAR_REQUEST                        0

In [3]:
candidate_rows = []

for intent, conversation_ids in family_candidates.items():

    # Skip intents with no candidate conversations
    if len(conversation_ids) == 0:
        continue

    for conversation_id in conversation_ids:

        # Get complete conversation
        conversation = amazon_df[
            amazon_df["conversation_id"] == conversation_id
        ].sort_values("created_at")

        # Build readable conversation text
        conversation_text = "\n".join(
            (
                "Customer: " if row["inbound"]
                else "AmazonHelp: "
            ) + str(row["clean_text"])
            for _, row in conversation.iterrows()
        )

        # Conversation length
        conversation_length = len(conversation)

        candidate_rows.append({
            "conversation_id": conversation_id,
            "conversation_length": conversation_length,
            "candidate_intent": intent,
            "candidate_source": "keyword_rule",
            "conversation_text": conversation_text
        })


# Create candidate DataFrame
candidate_pool = pd.DataFrame(candidate_rows)


# Remove duplicate conversation + candidate intent combinations
candidate_pool = candidate_pool.drop_duplicates(
    subset=[
        "conversation_id",
        "candidate_intent"
    ]
)


print("Candidate pool shape:", candidate_pool.shape)

print(
    "Unique conversations:",
    candidate_pool["conversation_id"].nunique()
)

print(
    "Unique candidate intents:",
    candidate_pool["candidate_intent"].nunique()
)

Candidate pool shape: (97553, 5)
Unique conversations: 50108
Unique candidate intents: 49

In [4]:
# ============================================================
# Cell 12 — Inspect Candidate Pool
# ============================================================

candidate_pool[
    [
        "conversation_id",
        "conversation_length",
        "candidate_intent",
        "candidate_source",
        "conversation_text"
    ]
].head(10)

,conversation_id,conversation_length,candidate_intent,candidate_source,conversation_text
0,2559,6,DELIVERY_DELAY,keyword_rule,"Customer: @AmazonHelp hello, I’m having an iss..."
1,11073,6,DELIVERY_DELAY,keyword_rule,Customer: @AmazonHelp isn't prime two day ship...
2,19137,218,DELIVERY_DELAY,keyword_rule,Customer: Don't get spooked by long delivery t...
3,42587,6,DELIVERY_DELAY,keyword_rule,Customer: @115821 I normally love you but the ...
4,77335,8,DELIVERY_DELAY,keyword_rule,Customer: Another delayed delivery @115830 ? E...
5,78873,6,DELIVERY_DELAY,keyword_rule,Customer: Items ordered on #CyberMonday from @...
6,86108,12,DELIVERY_DELAY,keyword_rule,Customer: @AmazonHelp Prime’s 2 day shipping a...
7,86208,4,DELIVERY_DELAY,keyword_rule,Customer: Today is the twins’ 4th Birthday. Th...
8,89101,2,DELIVERY_DELAY,keyword_rule,Customer: The whole perk of @115821 Prime is 2...
9,89316,4,DELIVERY_DELAY,keyword_rule,Customer: If I hear “it’s not our fault your p...

In [5]:

unique_candidate_ids = (
    candidate_pool["conversation_id"]
    .drop_duplicates()
)

candidate_sample_ids = unique_candidate_ids.sample(
    n=min(500, len(unique_candidate_ids)),
    random_state=42
)

candidate_pool_500 = candidate_pool[
    candidate_pool["conversation_id"].isin(
        candidate_sample_ids
    )
].copy()

print(
    "Unique candidate conversations:",
    candidate_pool_500["conversation_id"].nunique()
)

print(
    "Total candidate rows:",
    len(candidate_pool_500)
)

Unique candidate conversations: 500
Total candidate rows: 976

In [6]:
# ============================================================
# Cell 15 — Candidate Distribution by Intent
# ============================================================

candidate_distribution = (
    candidate_pool
    .groupby("candidate_intent")
    .size()
    .reset_index(name="candidate_count")
    .sort_values(
        "candidate_count",
        ascending=False
    )
)

print(candidate_distribution.to_string(index=False))

                       candidate_intent  candidate_count
                           APPRECIATION            16111
                    GENERAL_INFORMATION            13867
             CUSTOMER_SERVICE_COMPLAINT            10458
                               FEEDBACK             6440
                         REFUND_PROBLEM             5842
              DELIVERY_TRACKING_PROBLEM             4822
                         DEVICE_PROBLEM             4686
                COURIER_OR_DRIVER_ISSUE             4571
                  DELIVERY_NOT_RECEIVED             4047
ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM             3121
               PRIME_MEMBERSHIP_PROBLEM             2523
                    REPLACEMENT_PROBLEM             1983
                     ESCALATION_REQUEST             1976
          PROMOTION_OR_DISCOUNT_PROBLEM             1405
                         CHARGE_PROBLEM             1383
                SUPPORT_AGENT_COMPLAINT             1318
                  SCAM_OR_FRAUD_CONCERN             1286
                   PRODUCT_AVAILABILITY              978
                     AMAZON_PAY_PROBLEM              869
                  DELIVERED_BUT_MISSING              834
                           ORDER_STATUS              803
                       CASHBACK_PROBLEM              750
                   SUBSCRIPTION_PROBLEM              703
               DELIVERY_ATTEMPT_PROBLEM              679
                  WRONG_OR_MISSING_ITEM              580
                CONTEST_OR_QUIZ_INQUIRY              547
                DIGITAL_CONTENT_PROBLEM              539
                         RETURN_REQUEST              531
                     ORDER_CANCELLATION              517
              DELIVERY_LOCATION_PROBLEM              463
                         DELIVERY_DELAY              434
               UNRESOLVED_SUPPORT_ISSUE              385
          STREAMING_OR_PLAYBACK_PROBLEM              357
                 APP_OR_WEBSITE_PROBLEM              334
                ORDER_PLACEMENT_PROBLEM              255
                DAMAGED_DURING_DELIVERY              213
                  RETURN_PICKUP_PROBLEM              163
           SUSPICIOUS_EMAIL_OR_PHISHING              152
                       DUPLICATE_CHARGE              132
                PRIME_CHARGE_OR_RENEWAL               85
                     RETURN_ELIGIBILITY               83
                  PRIME_BENEFIT_PROBLEM               81
                    PRODUCT_INFORMATION               75
          UNAUTHORIZED_ACCOUNT_ACTIVITY               65
                        PAYMENT_FAILURE               55
                         RETURN_PROBLEM               24
                     ORDER_MODIFICATION               16
                   UNAUTHORIZED_PAYMENT                7
                      OFFER_ELIGIBILITY                5

In [7]:
# ============================================================
# Cell 16 — Candidate Distribution with Percentage
# ============================================================

total_candidate_rows = candidate_distribution["candidate_count"].sum()

candidate_distribution["percentage"] = (
    candidate_distribution["candidate_count"]
    / total_candidate_rows
    * 100
).round(2)

print(
    candidate_distribution.to_string(index=False)
)

                       candidate_intent  candidate_count  percentage
                           APPRECIATION            16111       16.52
                    GENERAL_INFORMATION            13867       14.21
             CUSTOMER_SERVICE_COMPLAINT            10458       10.72
                               FEEDBACK             6440        6.60
                         REFUND_PROBLEM             5842        5.99
              DELIVERY_TRACKING_PROBLEM             4822        4.94
                         DEVICE_PROBLEM             4686        4.80
                COURIER_OR_DRIVER_ISSUE             4571        4.69
                  DELIVERY_NOT_RECEIVED             4047        4.15
ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM             3121        3.20
               PRIME_MEMBERSHIP_PROBLEM             2523        2.59
                    REPLACEMENT_PROBLEM             1983        2.03
                     ESCALATION_REQUEST             1976        2.03
          PROMOTION_OR_DISCOUNT_PROBLEM             1405        1.44
                         CHARGE_PROBLEM             1383        1.42
                SUPPORT_AGENT_COMPLAINT             1318        1.35
                  SCAM_OR_FRAUD_CONCERN             1286        1.32
                   PRODUCT_AVAILABILITY              978        1.00
                     AMAZON_PAY_PROBLEM              869        0.89
                  DELIVERED_BUT_MISSING              834        0.85
                           ORDER_STATUS              803        0.82
                       CASHBACK_PROBLEM              750        0.77
                   SUBSCRIPTION_PROBLEM              703        0.72
               DELIVERY_ATTEMPT_PROBLEM              679        0.70
                  WRONG_OR_MISSING_ITEM              580        0.59
                CONTEST_OR_QUIZ_INQUIRY              547        0.56
                DIGITAL_CONTENT_PROBLEM              539        0.55
                         RETURN_REQUEST              531        0.54
                     ORDER_CANCELLATION              517        0.53
              DELIVERY_LOCATION_PROBLEM              463        0.47
                         DELIVERY_DELAY              434        0.44
               UNRESOLVED_SUPPORT_ISSUE              385        0.39
          STREAMING_OR_PLAYBACK_PROBLEM              357        0.37
                 APP_OR_WEBSITE_PROBLEM              334        0.34
                ORDER_PLACEMENT_PROBLEM              255        0.26
                DAMAGED_DURING_DELIVERY              213        0.22
                  RETURN_PICKUP_PROBLEM              163        0.17
           SUSPICIOUS_EMAIL_OR_PHISHING              152        0.16
                       DUPLICATE_CHARGE              132        0.14
                PRIME_CHARGE_OR_RENEWAL               85        0.09
                     RETURN_ELIGIBILITY               83        0.09
                  PRIME_BENEFIT_PROBLEM               81        0.08
                    PRODUCT_INFORMATION               75        0.08
          UNAUTHORIZED_ACCOUNT_ACTIVITY               65        0.07
                        PAYMENT_FAILURE               55        0.06
                         RETURN_PROBLEM               24        0.02
                     ORDER_MODIFICATION               16        0.02
                   UNAUTHORIZED_PAYMENT                7        0.01
                      OFFER_ELIGIBILITY                5        0.01

In [8]:
for conversation_id, group in candidate_pool_500.groupby(
    "conversation_id"
):

    print("=" * 100)
    print(f"Conversation: {conversation_id}")
    print("=" * 100)

    print(
        "Conversation length:",
        group["conversation_length"].iloc[0]
    )

    print(
        "Candidate intent(s):",
        ", ".join(group["candidate_intent"].unique())
    )

    print("\nConversation:")
    print(group["conversation_text"].iloc[0])

    print("\n")

====================================================================================================
Conversation: 16758
====================================================================================================
Conversation length: 6
Candidate intent(s): REFUND_PROBLEM

Conversation:
Customer: @AmazonHelp fuck you guys. Canceling Prime. Not gonna do business with you guys ever again.
AmazonHelp: @119697 This isn't how we want you to feel. We'd like to help, if possible. Please let us know more about what's going.
Customer: @AmazonHelp No one knows what to do to get my refund back to me!
Customer: @AmazonHelp You know it's some fucked up shit when you gotta conference call @116827 and @AmazonHelp
AmazonHelp: @119697 I'm sorry for the trouble. Generally, the bank can issue a refund to the new active card on file. Please keep us updated.
Customer: @AmazonHelp No card on file after 30 days. Refund send back to merchant. That's you.


====================================================================================================
Conversation: 21586
====================================================================================================
Conversation length: 53
Candidate intent(s): DELIVERY_NOT_RECEIVED, COURIER_OR_DRIVER_ISSUE, PRODUCT_AVAILABILITY, REFUND_PROBLEM, CUSTOMER_SERVICE_COMPLAINT, SUPPORT_AGENT_COMPLAINT, ESCALATION_REQUEST, GENERAL_INFORMATION, FEEDBACK, APPRECIATION

Conversation:
Customer: @115850 order Id: 171-0365118-2187508. Stop fooling around and deliver the package, and I want compensation for your delivery agent being rude to my wife, and trust me this is not the first time this is happening..I want a resolution
AmazonHelp: @120701 Please don’t provide your order details as we consider them to be personal info. Our Twitter page is visible to public. (2/2)
AmazonHelp: @120701 Apologies for the unpleasant experience. Please contact us here: & we'll take corrective actions.(1/2)
Customer: @AmazonHelp Trust me it useless to narrate my experience in the app feedback...I want a resolution... And commitment that this won't be repeated and a compensation
Customer: @AmazonHelp Trust me your customer service reps are really pathetic. I have a question, have u ever had listened to phone conversation of reps and customer...I need compensation and u need to be professional
AmazonHelp: @120701 I'm sorry for the trouble. We will definitely make sure such an instance does not get repeated. Compensation policies (1/2)
AmazonHelp: @120701 -are not available in amazon. (2/2)
Customer: @AmazonHelp Sure..so if compensation is not available...can I name and shame you guys...because u guys are pathetic..can u quickly tell me ur name and employee ID and also ur escalation point of contact..because I am not sitting quiet
Customer: @AmazonHelp Also..can u tell me precisely that when thieves like you are giving me my shipment. And trust me it's not COD, it's prepaid and u r denying delivery..I want a call to resolve this idiots
AmazonHelp: @120701 on this as feedback with the team internally for a review. 2/2
AmazonHelp: @120701 I'm sorry but I wouldn't' be able to disclose those details. However, I'll be sure to share your comments 1/2
Customer: @AmazonHelp Feedback? Are you kidding me? Where is my money and the package...bloddy idiots I am the prime customer and I want the shipment to be delivered rite now...I don't care about ur internal review...get me ur escalation point of contact to call me
AmazonHelp: @120701 We understand your concern. We’d like to help you; please fill this form: and we’ll contact you soon.
Customer: @AmazonHelp Just did it...I want a commitment of my product or money rite now..be a man and do the rite thing by today, either deliver or refund rite now..else I am going to consumer court with ur replies
AmazonHelp: @120701 Thank you for the confirmation. We understand the importance of this issue to you. 1/2
AmazonHelp: @120701 I assure you that our team will get back with an update. Request you to wait till then. 2/2
Customer: @AmazonHelp Be a man of your words and come up with a solution by today. And also I am expecting call from ur management? Is it possible..just disclose it in public forum and I'll take this with consumer court
AmazonHelp: @120701 We will definitely get back to you. Request you to wait till then. Your patience here will be highly appreciated.
Customer: @AmazonHelp Ohhh come on...don't be a freak...who has kept u on the job? You are not committing a time when u would take an action? Also confirm whether you will be calling me up by today end of the day? Only if u have questions to these answers you reply...
AmazonHelp: @120701 I understand waiting could be tiresome but rest assured, the concerned team is working on a resolution for you.
Customer: @AmazonHelp Ohhh so this how u treat a prime customer...unless u provide me resolution don't reply on this and also I am tagging big people from Amazon to look into it...stop send me tweets with empathy...I don't need it...m the customer, I'll go somewhere else
AmazonHelp: @120701 As the details are shared from the link mentioned earlier, we'd get back to you soon with an update.
Customer: @AmazonHelp Hellos idiots... 9762642673 I got this number today for the delivery guy...from past 2hours he's saying he's coming in 2min...what the fuck is wrong with u shameless people...don't write words of empathy
Customer: @AmazonHelp @115850 @AmazonHelp what are you idiots doing from yesterday...do u have basic sense...
AmazonHelp: @120701 Apologies, please fill this form: and we'll get back to you right away.
Customer: @AmazonHelp R u bastard? Don't u know I have already sent the form yesterday...moron...
Customer: @AmazonHelp 9762642673 call on this number n tell him to deliver
AmazonHelp: @120701 Request you to wait till 8:00 pm for an update on delivery. Also, as you have filled the form, you will receive an email 1/2
AmazonHelp: @120701 communication here: Appreciate your patience. 2/2
Customer: @AmazonHelp Chutiya Hai Kya tu...from yesterday u guys are delivering? Madarchod
AmazonHelp: @120701 I understand you are yet to receive your order. Please wait for our team to reach out to you soon.
Customer: @AmazonHelp Good morning Amazon idiots... third day in a row... today's delivery guys number 70385 67720....can u idiots call him and ask him to deliver... Bunch of incompetetive morons...get this sorted out today...n don't use empathy n sympathy
AmazonHelp: @120701 I get your concern, please check for an email from our team here:
Customer: @AmazonHelp Are you guys nuts? How can u ask me to wait... bloddy idiots from past three days I am waiting...what r u guys? Stupid assholes? U don't have integrity
AmazonHelp: @120701 I'm sorry for the disappointment with your order delivery, you should be receiving a correspondence from us to your 1/3
AmazonHelp: @120701 registered email account post submitting the form here: can you check for the following 2/3
AmazonHelp: @120701 correspondence & reply? I haven't seen any details with your name or Twitter handle till now. 3/3
Customer: @AmazonHelp I have already given the order details you moron...what are u not able to find out...go figure out yourself...stupid ass
AmazonHelp: @120701 Quite a wide range of vocabulary you got there. If you have filled in the details earlier, I believe we must have already 1/2
AmazonHelp: @120701 reached out via email. Kindly check for the last correspondence from us here: and respond to it. 2/2
Customer: @AmazonHelp Really AB? Why don't you shove it up somewhere appropriately and get your smartest ass people to resolve the query instead of appreciating my vocab...I would love to meet u in person and would like to thank u..let me know when u r interested
Customer: @AmazonHelp What last correspondence idiots? Check this screenshot and give me the appropriate email that you are talking about...u chutiyas are asking me for a feedback..first get it delivered bsdk
Customer: @AmazonHelp
AmazonHelp: @120701 Your thanks has been heartily accepted here. I understand you're upset but that doesn't warrant name-calling. 1/3
AmazonHelp: @120701 FYI, I just checked again, and contrary to your confirmation, we haven't received any details as requested 2/3
AmazonHelp: @120701 earlier by , or . Kindly drop in your details using the link provided so that we can help you with a resolution 3/3
Customer: @AmazonHelp Allrite..I understand that you are a special child, we will do it once again for you..here are the order details: 171-0365118-2187508. For one last time I m telling u, I'll not again fill up any of ur forms...because u guys are retards and can't understand a simple language
Customer: @AmazonHelp 2- are you trying to tell me that if I don't fill up this form u will not resolve my query? How can u guys be so dumbass, check with ur customer care rep how many times I have called and haven't got resolution, it doesn't count? #TaareZameenPar?
AmazonHelp: @120701 Posting the details here on Twitter won't help, Harshal. You need to drop them using the link sent by as we 1/3
AmazonHelp: @120701 don't have access to your account details over Twitter. Unless the form is filled we wouldn't be able to offer 2/3
AmazonHelp: @120701 any further insight in this case. Also, please don't provide your order details as our Twitter page is visible to public. 3/3
Customer: @AmazonHelp Ok tu ek kaam kar an...apni MAA chuda...bhosadike...to hell with you guys...this is my contact number, tell ur reps that I'll call and will screw ur happiness : 8793681285
Customer: @AmazonHelp Kyu be chutiye...even after giving u my contact details and oder details u guys are unable to track and deliver it once again... #TaareZameenPar


====================================================================================================
Conversation: 22483
====================================================================================================
Conversation length: 3
Candidate intent(s): ORDER_PLACEMENT_PROBLEM

Conversation:
Customer: @115850 I had ordered a RedMi 4, 4GB, 64Gb. delivered faulty piece, want re-order the product @1504 price. was going out nxt day.
AmazonHelp: @120915 Apologies on receiving a faulty product. You may visit the website and place an order 1/2
AmazonHelp: @120915 for the phone which you are looking for. 2/2


====================================================================================================
Conversation: 61035
====================================================================================================
Conversation length: 9
Candidate intent(s): DELIVERY_NOT_RECEIVED, COURIER_OR_DRIVER_ISSUE, DELIVERY_TRACKING_PROBLEM

Conversation:
Customer: Cried for 2 hrs straight this evening ‘cause neither @122232 or @AmazonHelp could be bothered to deliver to me. So yes, I am still pregnant.
AmazonHelp: @129967 I'm so sorry you didn't receive your package! Did we miss the date confirmed in the e-mail:
Customer: @AmazonHelp Yes it was supposed to be delivered yesterday, couldn’t find my address, I spoke to CS today to pass details over to courier and was told
Customer: @AmazonHelp I’d have my order today. Luckily I didn’t hold my breath
Customer: @AmazonHelp Can you find out if I’m getting my parcel today please?
AmazonHelp: @129967 What is the latest tracking scan? Have you reached out to the courier for an update on the current status or your parcel?
Customer: @AmazonHelp I don’t know who the courier is. It says it’s coming today but it said that yesterday and the day before
AmazonHelp: @129967 As we're unable to view your account via Twitter,pls contact here: so we can look into this.
Customer: @AmazonHelp Well it worked so well yesterday


====================================================================================================
Conversation: 65698
====================================================================================================
Conversation length: 14
Candidate intent(s): REPLACEMENT_PROBLEM, STREAMING_OR_PLAYBACK_PROBLEM, FEEDBACK, APPRECIATION

Conversation:
Customer: Alright, #Amazon. Ordered a CD. It came broken. Ordered a replacement. It came broken. Ordered a second replacement. Yes, it too came broken. It seems as if fluffy jiffy envelopes don't work as good as cardboard ones. Can't do no more exchanges, alas. Help, @AmazonHelp!
AmazonHelp: @131035 I'm so sorry for the order issues. I know how frustrating that can be and we'll do our best to help! Please call in so we can take a closer look at the problem together here:
Customer: .@AmazonHelp I’m kinda done - I spent 1.5 hours in talks with four (!) different hotliners which ended up not being able to help until I bought more (!) to have my cart be above $25 so I could return three other broken CDs. Will return & scout local stores instead. @115851
AmazonHelp: @131035 Were you advised as to why your cart had to be above $25? Were we able to provide a return label for the broken CDs?
Customer: @AmazonHelp The CDs could not be exchanged so I had to reorder. Alas, some were add-on CDs that could not be ordered by themselves so I had to increase the cart value to $25 by buying more. Which I did. Two CDs arrived okay, another one broken. Returned that again to get in brkn.
Customer: @AmazonHelp So at this point I am led to believe that Amazon does not care about legacy media any more, else it would make sure it would arrive undamaged. Streaming of course makes more money long-term than selling an album once, I get it.
AmazonHelp: @131035 Apologies for the trouble this has caused, Roland. We're always looking for ways to improve! Please provide direct feedback regarding packaging here:
Customer: @AmazonHelp I also have provided feedback throughout all this and for most of my packages over the last years. Zero effect, so it seems that I might as well save the time and don’t do it anymore. :/
Customer: @AmazonHelp Also, not sure why I should give feedback in the UK if I live in the US. ;)
AmazonHelp: @131035 Apologizes for the wrong link Roland, here is the correct one for US:
AmazonHelp: @131035 Sorry to hear your received multiple broken CDs. Was the carrier the same for all orders?
Customer: @AmazonHelp Correct, but not so much the carrier than the packaging’s fault. There is a reason stores don’t sell eggs in soft envelopes but in sturdy cardboard. ;)
AmazonHelp: @131035 Thank you for letting us know. Can I ask if you provided feedback via the link provided by ?
Customer: @AmazonHelp I just did a bit earlier.


====================================================================================================
Conversation: 65777
====================================================================================================
Conversation length: 4
Candidate intent(s): APPRECIATION

Conversation:
Customer: When will @115830 dispatch my DVDs? I’m not (that) impatient or anything, I just really want to finally have the boxset in my hands and mesmerizing this collection ️
AmazonHelp: @131045 Hi, your order can be dispatched right up until close to the delivery date. A week can seem like forever when it's the Gilmore Girls you're waiting for! Let us know if you don't receive your order by the date advised.
Customer: @AmazonHelp Thank you for the quick answer, I will if it happens!
AmazonHelp: @131045 Thank you:) You have a lovely day!


====================================================================================================
Conversation: 69971
====================================================================================================
Conversation length: 6
Candidate intent(s): COURIER_OR_DRIVER_ISSUE, WRONG_OR_MISSING_ITEM, APPRECIATION

Conversation:
Customer: @AmazonHelp @115850 delivered my prepaid order of Rs 2000 to a different address. That's not it delivered the wrong item too. Check DM.
AmazonHelp: @131829 We'd like to check this for you. Kindly share your details here: and I'll look into this.
Customer: @AmazonHelp done. Hope someone helps and just doesn't give us false promises this time
AmazonHelp: @131829 Thanks for sharing your details. We'll check and get in touch with you with an update at the earliest. Appreciate your patience until then.
Customer: @AmazonHelp customer care calls and gives courier contact and they don't pick up the call. AGAIN. Is this how "on priority" works?
AmazonHelp: @131829 Apologies for the inconvenience you had with our Courier. We have sent a correspondence to your registered email ID. Please check and reply to the same, we will look into it.


====================================================================================================
Conversation: 80515
====================================================================================================
Conversation length: 3
Candidate intent(s): COURIER_OR_DRIVER_ISSUE, REPLACEMENT_PROBLEM, APPRECIATION

Conversation:
Customer: *Slow clap* to the @115830 delivery driver who left my package 'next to the wheelie bin' on collection day. Was it there? Was it fu...
AmazonHelp: @133879 I'm so sorry to hear your package was delivered as such! Please reach out to us here: so we may further assist.
Customer: @AmazonHelp already done thanks. Replacement package coming tomorrow. Just think you may want to train your delivery drivers that using waste bins in any way is not a good idea


====================================================================================================
Conversation: 86260
====================================================================================================
Conversation length: 4
Candidate intent(s): DEVICE_PROBLEM, ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM, APPRECIATION

Conversation:
Customer: Dear @115821, please don't force me to use German jobs on my Alexa. My home is English-speaking, yet I'm expected to speak German to use my Phillips Hue and Fire TV.
Customer: @115821 If I was desperate enough, in theory, I could fake my account location to US, but then, incidentally, that process is broken and throws an error.
AmazonHelp: @134832 You can change the language for your Alexa devices within the Alexa app. Please note that the language settings have to be changed individually for each device. 1. Open the Alexa app & select "Settings" 2. Select your device. 3. Select "Language" Regards
Customer: @AmazonHelp MS, thanks, but Phillips Hue won't work in English in Germany. It'll ask you to switch the device language to German (and also crash in the process). Fire TV stick and Alexa will not even display a link option with both devices set to English while connected to a German account.


====================================================================================================
Conversation: 93655
====================================================================================================
Conversation length: 2
Candidate intent(s): REFUND_PROBLEM

Conversation:
Customer: @116090 I just called to as why my order that had 2 day delivery had not shipped yet. 2 days is today. Had to cancel it as expediting would delay it. Now I’m waiting for confirmation and refund. It’s gone from my order history. Where is it?
AmazonHelp: @136298 Refunds can take 3-5 business days to be received by your financial institution. For more about refund processing time, check out our help pages here: - Josh M


====================================================================================================
Conversation: 103062
====================================================================================================
Conversation length: 6
Candidate intent(s): CONTEST_OR_QUIZ_INQUIRY

Conversation:
Customer: @AmazonHelp where the winners list?
AmazonHelp: @132732 The contest results will be announced at any moment now.
Customer: @AmazonHelp Hlo plz reply....how to find out winners?

In [9]:
golden_set = pd.DataFrame(
    columns=[
        "conversation_id",
        "conversation_text",
        "candidate_intent",
        "gold_intent",
        "label_reason",
        "difficulty"
    ]
)

In [10]:
sampling_plan = candidate_distribution.copy()

# Classify each intent
def classify_group(count):
    if count > 1000:
        return "Common"
    elif count >= 100:
        return "Medium"
    elif count > 0:
        return "Rare"
    else:
        return "No candidates"


sampling_plan["group"] = (
    sampling_plan["candidate_count"]
    .apply(classify_group)
)


# Initial allocation
def initial_target(group):
    if group == "Common":
        return 6
    elif group == "Medium":
        return 4
    elif group == "Rare":
        return 2
    else:
        return 0


sampling_plan["target_samples"] = (
    sampling_plan["group"]
    .apply(initial_target)
)


print(sampling_plan.to_string(index=False))

print(
    "\nInitial total:",
    sampling_plan["target_samples"].sum()
)

                       candidate_intent  candidate_count  percentage  group  target_samples
                           APPRECIATION            16111       16.52 Common               6
                    GENERAL_INFORMATION            13867       14.21 Common               6
             CUSTOMER_SERVICE_COMPLAINT            10458       10.72 Common               6
                               FEEDBACK             6440        6.60 Common               6
                         REFUND_PROBLEM             5842        5.99 Common               6
              DELIVERY_TRACKING_PROBLEM             4822        4.94 Common               6
                         DEVICE_PROBLEM             4686        4.80 Common               6
                COURIER_OR_DRIVER_ISSUE             4571        4.69 Common               6
                  DELIVERY_NOT_RECEIVED             4047        4.15 Common               6
ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM             3121        3.20 Common               6
               PRIME_MEMBERSHIP_PROBLEM             2523        2.59 Common               6
                    REPLACEMENT_PROBLEM             1983        2.03 Common               6
                     ESCALATION_REQUEST             1976        2.03 Common               6
          PROMOTION_OR_DISCOUNT_PROBLEM             1405        1.44 Common               6
                         CHARGE_PROBLEM             1383        1.42 Common               6
                SUPPORT_AGENT_COMPLAINT             1318        1.35 Common               6
                  SCAM_OR_FRAUD_CONCERN             1286        1.32 Common               6
                   PRODUCT_AVAILABILITY              978        1.00 Medium               4
                     AMAZON_PAY_PROBLEM              869        0.89 Medium               4
                  DELIVERED_BUT_MISSING              834        0.85 Medium               4
                           ORDER_STATUS              803        0.82 Medium               4
                       CASHBACK_PROBLEM              750        0.77 Medium               4
                   SUBSCRIPTION_PROBLEM              703        0.72 Medium               4
               DELIVERY_ATTEMPT_PROBLEM              679        0.70 Medium               4
                  WRONG_OR_MISSING_ITEM              580        0.59 Medium               4
                CONTEST_OR_QUIZ_INQUIRY              547        0.56 Medium               4
                DIGITAL_CONTENT_PROBLEM              539        0.55 Medium               4
                         RETURN_REQUEST              531        0.54 Medium               4
                     ORDER_CANCELLATION              517        0.53 Medium               4
              DELIVERY_LOCATION_PROBLEM              463        0.47 Medium               4
                         DELIVERY_DELAY              434        0.44 Medium               4
               UNRESOLVED_SUPPORT_ISSUE              385        0.39 Medium               4
          STREAMING_OR_PLAYBACK_PROBLEM              357        0.37 Medium               4
                 APP_OR_WEBSITE_PROBLEM              334        0.34 Medium               4
                ORDER_PLACEMENT_PROBLEM              255        0.26 Medium               4
                DAMAGED_DURING_DELIVERY              213        0.22 Medium               4
                  RETURN_PICKUP_PROBLEM              163        0.17 Medium               4
           SUSPICIOUS_EMAIL_OR_PHISHING              152        0.16 Medium               4
                       DUPLICATE_CHARGE              132        0.14 Medium               4
                PRIME_CHARGE_OR_RENEWAL               85        0.09   Rare               2
                     RETURN_ELIGIBILITY               83        0.09   Rare               2
                  PRIME_BENEFIT_PROBLEM               81        0.08   Rare               2
                    PRODUCT_INFORMATION               75        0.08   Rare               2
          UNAUTHORIZED_ACCOUNT_ACTIVITY               65        0.07   Rare               2
                        PAYMENT_FAILURE               55        0.06   Rare               2
                         RETURN_PROBLEM               24        0.02   Rare               2
                     ORDER_MODIFICATION               16        0.02   Rare               2
                   UNAUTHORIZED_PAYMENT                7        0.01   Rare               2
                      OFFER_ELIGIBILITY                5        0.01   Rare               2

Initial total: 210

In [11]:
# ============================================================
# Final Golden Set Sampling Plan
# ============================================================

# Start from the candidate distribution
sampling_plan = candidate_distribution.copy()


# ------------------------------------------------------------
# 1. Classify intents into Common / Medium / Rare
# ------------------------------------------------------------

def classify_group(count):

    if count > 1000:
        return "Common"

    elif count >= 100:
        return "Medium"

    elif count > 0:
        return "Rare"

    else:
        return "No candidates"


sampling_plan["group"] = (
    sampling_plan["candidate_count"]
    .apply(classify_group)
)


# ------------------------------------------------------------
# 2. Assign stratified target samples
# ------------------------------------------------------------

def assign_target(group):

    if group == "Common":
        return 5

    elif group == "Medium":
        return 4

    elif group == "Rare":
        return 2

    else:
        return 0


sampling_plan["target_samples"] = (
    sampling_plan["group"]
    .apply(assign_target)
)


# ------------------------------------------------------------
# 3. Mark these as STRATIFIED
# ------------------------------------------------------------

sampling_plan["sampling_type"] = "STRATIFIED"


# ------------------------------------------------------------
# 4. Add 7 difficult cases
# ------------------------------------------------------------

difficult_row = pd.DataFrame({
    "candidate_intent": ["DIFFICULT_CASES"],
    "candidate_count": [None],
    "percentage": [None],
    "group": ["—"],
    "target_samples": [7],
    "sampling_type": ["DIFFICULT"]
})


# Add difficult row
sampling_plan = pd.concat(
    [
        sampling_plan,
        difficult_row
    ],
    ignore_index=True
)


# ------------------------------------------------------------
# 5. Arrange columns
# ------------------------------------------------------------

sampling_plan = sampling_plan[
    [
        "candidate_intent",
        "candidate_count",
        "group",
        "target_samples",
        "sampling_type"
    ]
]


# ------------------------------------------------------------
# 6. Sort intents
# ------------------------------------------------------------

# Keep DIFFICULT_CASES at the bottom
normal_intents = sampling_plan[
    sampling_plan["candidate_intent"] != "DIFFICULT_CASES"
].sort_values(
    "candidate_count",
    ascending=False
)

difficult_cases = sampling_plan[
    sampling_plan["candidate_intent"] == "DIFFICULT_CASES"
]

sampling_plan = pd.concat(
    [
        normal_intents,
        difficult_cases
    ],
    ignore_index=True
)


# ------------------------------------------------------------
# 7. Display final sampling plan
# ------------------------------------------------------------

print(
    sampling_plan.to_string(index=False)
)


# ------------------------------------------------------------
# 8. Verify total
# ------------------------------------------------------------

total_samples = sampling_plan["target_samples"].sum()

print("\nTotal target samples:", total_samples)

assert total_samples == 200, (
    f"Expected 200 samples, but got {total_samples}"
)

print("✅ Sampling plan is exactly 200.")

                       candidate_intent candidate_count  group  target_samples sampling_type
                           APPRECIATION           16111 Common               5    STRATIFIED
                    GENERAL_INFORMATION           13867 Common               5    STRATIFIED
             CUSTOMER_SERVICE_COMPLAINT           10458 Common               5    STRATIFIED
                               FEEDBACK            6440 Common               5    STRATIFIED
                         REFUND_PROBLEM            5842 Common               5    STRATIFIED
              DELIVERY_TRACKING_PROBLEM            4822 Common               5    STRATIFIED
                         DEVICE_PROBLEM            4686 Common               5    STRATIFIED
                COURIER_OR_DRIVER_ISSUE            4571 Common               5    STRATIFIED
                  DELIVERY_NOT_RECEIVED            4047 Common               5    STRATIFIED
ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM            3121 Common               5    STRATIFIED
               PRIME_MEMBERSHIP_PROBLEM            2523 Common               5    STRATIFIED
                    REPLACEMENT_PROBLEM            1983 Common               5    STRATIFIED
                     ESCALATION_REQUEST            1976 Common               5    STRATIFIED
          PROMOTION_OR_DISCOUNT_PROBLEM            1405 Common               5    STRATIFIED
                         CHARGE_PROBLEM            1383 Common               5    STRATIFIED
                SUPPORT_AGENT_COMPLAINT            1318 Common               5    STRATIFIED
                  SCAM_OR_FRAUD_CONCERN            1286 Common               5    STRATIFIED
                   PRODUCT_AVAILABILITY             978 Medium               4    STRATIFIED
                     AMAZON_PAY_PROBLEM             869 Medium               4    STRATIFIED
                  DELIVERED_BUT_MISSING             834 Medium               4    STRATIFIED
                           ORDER_STATUS             803 Medium               4    STRATIFIED
                       CASHBACK_PROBLEM             750 Medium               4    STRATIFIED
                   SUBSCRIPTION_PROBLEM             703 Medium               4    STRATIFIED
               DELIVERY_ATTEMPT_PROBLEM             679 Medium               4    STRATIFIED
                  WRONG_OR_MISSING_ITEM             580 Medium               4    STRATIFIED
                CONTEST_OR_QUIZ_INQUIRY             547 Medium               4    STRATIFIED
                DIGITAL_CONTENT_PROBLEM             539 Medium               4    STRATIFIED
                         RETURN_REQUEST             531 Medium               4    STRATIFIED
                     ORDER_CANCELLATION             517 Medium               4    STRATIFIED
              DELIVERY_LOCATION_PROBLEM             463 Medium               4    STRATIFIED
                         DELIVERY_DELAY             434 Medium               4    STRATIFIED
               UNRESOLVED_SUPPORT_ISSUE             385 Medium               4    STRATIFIED
          STREAMING_OR_PLAYBACK_PROBLEM             357 Medium               4    STRATIFIED
                 APP_OR_WEBSITE_PROBLEM             334 Medium               4    STRATIFIED
                ORDER_PLACEMENT_PROBLEM             255 Medium               4    STRATIFIED
                DAMAGED_DURING_DELIVERY             213 Medium               4    STRATIFIED
                  RETURN_PICKUP_PROBLEM             163 Medium               4    STRATIFIED
           SUSPICIOUS_EMAIL_OR_PHISHING             152 Medium               4    STRATIFIED
                       DUPLICATE_CHARGE             132 Medium               4    STRATIFIED
                PRIME_CHARGE_OR_RENEWAL              85   Rare               2    STRATIFIED
                     RETURN_ELIGIBILITY              83   Rare               2    STRATIFIED
                  PRIME_BENEFIT_PROBLEM              81   Rare               2    STRATIFIED
                    PRODUCT_INFORMATION              75   Rare               2    STRATIFIED
          UNAUTHORIZED_ACCOUNT_ACTIVITY              65   Rare               2    STRATIFIED
                        PAYMENT_FAILURE              55   Rare               2    STRATIFIED
                         RETURN_PROBLEM              24   Rare               2    STRATIFIED
                     ORDER_MODIFICATION              16   Rare               2    STRATIFIED
                   UNAUTHORIZED_PAYMENT               7   Rare               2    STRATIFIED
                      OFFER_ELIGIBILITY               5   Rare               2    STRATIFIED
                        DIFFICULT_CASES            None      —               7     DIFFICULT

Total target samples: 200
✅ Sampling plan is exactly 200.

C:\Users\Nihelesh M U\AppData\Local\Temp\ipykernel_12352\582712094.py:81: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  sampling_plan = pd.concat(

In [12]:
# ============================================================
# Select Golden Set Conversations
# ============================================================

import pandas as pd


selected_samples = []


# ------------------------------------------------------------
# 1. Loop through every intent in the sampling plan
# ------------------------------------------------------------

for _, plan_row in sampling_plan.iterrows():

    intent = plan_row["candidate_intent"]
    target_samples = int(plan_row["target_samples"])

    # Skip the artificial DIFFICULT_CASES row for now
    if intent == "DIFFICULT_CASES":
        continue

    # Skip intents with zero target samples
    if target_samples == 0:
        continue

    # --------------------------------------------------------
    # Find conversations belonging to this candidate intent
    # --------------------------------------------------------

    candidates = candidate_pool[
        candidate_pool["candidate_intent"] == intent
    ].copy()

    # Remove duplicate conversation IDs
    candidates = candidates.drop_duplicates(
        subset=["conversation_id"]
    )

    # --------------------------------------------------------
    # Check that enough candidates exist
    # --------------------------------------------------------

    if len(candidates) < target_samples:

        print(
            f"WARNING: {intent} has only "
            f"{len(candidates)} candidates, "
            f"but {target_samples} were requested."
        )

        target_samples = len(candidates)

    # --------------------------------------------------------
    # Randomly select conversations
    # --------------------------------------------------------

    selected = candidates.sample(
        n=target_samples,
        random_state=42
    ).copy()

    # --------------------------------------------------------
    # Get information from sampling plan
    # --------------------------------------------------------

    selected["candidate_count"] = (
        plan_row["candidate_count"]
    )

    selected["group"] = (
        plan_row["group"]
    )

    selected["sampling_type"] = (
        "STRATIFIED"
    )

    # --------------------------------------------------------
    # Initially leave gold-label fields empty
    # --------------------------------------------------------

    selected["gold_intent"] = pd.NA
    selected["label_reason"] = pd.NA
    selected["difficulty"] = pd.NA

    # --------------------------------------------------------
    # Keep required columns
    # --------------------------------------------------------

    selected = selected[
        [
            "conversation_id",
            "candidate_intent",
            "candidate_count",
            "group",
            "sampling_type",
            "gold_intent",
            "label_reason",
            "difficulty"
        ]
    ]

    selected_samples.append(selected)


# ------------------------------------------------------------
# 2. Combine all sampled conversations
# ------------------------------------------------------------

golden_set = pd.concat(
    selected_samples,
    ignore_index=True
)


# ------------------------------------------------------------
# 3. Remove accidental duplicate conversations
# ------------------------------------------------------------

golden_set = golden_set.drop_duplicates(
    subset=["conversation_id"]
).reset_index(drop=True)


# ------------------------------------------------------------
# 4. Display result
# ------------------------------------------------------------

print(
    "Selected conversations:",
    len(golden_set)
)

print(
    "Unique conversations:",
    golden_set["conversation_id"].nunique()
)

print("\nSampling type:")
print(
    golden_set["sampling_type"].value_counts()
)

print("\nCandidate intent distribution:")
print(
    golden_set["candidate_intent"].value_counts()
)

Selected conversations: 192
Unique conversations: 192

Sampling type:
sampling_type
STRATIFIED    192
Name: count, dtype: int64

Candidate intent distribution:
candidate_intent
APPRECIATION                               5
GENERAL_INFORMATION                        5
CUSTOMER_SERVICE_COMPLAINT                 5
FEEDBACK                                   5
REFUND_PROBLEM                             5
DELIVERY_TRACKING_PROBLEM                  5
DEVICE_PROBLEM                             5
COURIER_OR_DRIVER_ISSUE                    5
DELIVERY_NOT_RECEIVED                      5
ACCOUNT_LINKING_OR_CONNECTIVITY_PROBLEM    5
PRIME_MEMBERSHIP_PROBLEM                   5
REPLACEMENT_PROBLEM                        5
ESCALATION_REQUEST                         5
PROMOTION_OR_DISCOUNT_PROBLEM              5
CHARGE_PROBLEM                             5
SUPPORT_AGENT_COMPLAINT                    5
SCAM_OR_FRAUD_CONCERN                      5
PRODUCT_AVAILABILITY                       4
DELIVERED_BUT_MISSING                      4
ORDER_STATUS                               4
CASHBACK_PROBLEM                           4
DELIVERY_ATTEMPT_PROBLEM                   4
SUBSCRIPTION_PROBLEM                       4
WRONG_OR_MISSING_ITEM                      4
CONTEST_OR_QUIZ_INQUIRY                    4
DELIVERY_LOCATION_PROBLEM                  4
DIGITAL_CONTENT_PROBLEM                    4
RETURN_REQUEST                             4
ORDER_CANCELLATION                         4
UNRESOLVED_SUPPORT_ISSUE                   4
DELIVERY_DELAY                             4
STREAMING_OR_PLAYBACK_PROBLEM              4
APP_OR_WEBSITE_PROBLEM                     4
SUSPICIOUS_EMAIL_OR_PHISHING               4
ORDER_PLACEMENT_PROBLEM                    4
DAMAGED_DURING_DELIVERY                    4
RETURN_PICKUP_PROBLEM                      4
DUPLICATE_CHARGE                           4
AMAZON_PAY_PROBLEM                         3
PRIME_CHARGE_OR_RENEWAL                    2
RETURN_ELIGIBILITY                         2
PRIME_BENEFIT_PROBLEM                      2
PRODUCT_INFORMATION                        2
UNAUTHORIZED_ACCOUNT_ACTIVITY              2
PAYMENT_FAILURE                            2
RETURN_PROBLEM                             2
ORDER_MODIFICATION                         2
UNAUTHORIZED_PAYMENT                       2
OFFER_ELIGIBILITY                          2
Name: count, dtype: int64

In [13]:
# ============================================================
# Add conversation text
# ============================================================

conversation_texts = (
    candidate_pool[
        [
            "conversation_id",
            "conversation_text"
        ]
    ]
    .drop_duplicates("conversation_id")
)


golden_set = golden_set.merge(
    conversation_texts,
    on="conversation_id",
    how="left"
)

In [14]:
# ============================================================
# Final Golden Set column order
# ============================================================

golden_set = golden_set[
    [
        "conversation_id",
        "conversation_text",
        "candidate_intent",
        "candidate_count",
        "group",
        "sampling_type",
        "gold_intent",
        "label_reason",
        "difficulty"
    ]
]

print(golden_set.shape)

golden_set.head()

(192, 9)

,conversation_id,conversation_text,candidate_intent,candidate_count,group,sampling_type,gold_intent,label_reason,difficulty
0,2447398,Customer: @115821 thanks for the gift card tha...,APPRECIATION,16111,Common,STRATIFIED,NaN,NaN,NaN
1,2686757,Customer: the second prime order in a row that...,APPRECIATION,16111,Common,STRATIFIED,NaN,NaN,NaN
2,2967720,Customer: @115821 how can I apply for your NC ...,APPRECIATION,16111,Common,STRATIFIED,NaN,NaN,NaN
3,930181,Customer: @AmazonHelp Recently moved from Kind...,APPRECIATION,16111,Common,STRATIFIED,NaN,NaN,NaN
4,1132075,Customer: hi @AmazonHelp twitter rejected my r...,APPRECIATION,16111,Common,STRATIFIED,NaN,NaN,NaN

In [15]:
golden_set.to_csv(
    "../data/processed/amazonhelp_golden_set.csv",
    index=False
)

print("✅ Golden Set saved.")

PermissionError: [Errno 13] Permission denied: '../data/processed/amazonhelp_golden_set.csv'

In [16]:
# ============================================================
# Display complete conversations for the selected 200 IDs
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1. Selected 200 conversation IDs
# ------------------------------------------------------------

selected_conversation_ids = [
    2447398,
    2686757,
    2967720,
    930181,
    1132075,
    1551751,
    346732,
    1447950,
    863820,
    525543,
    1231224,
    2841686,
    2369649,
    1699857,
    2283867,
    2408704,
    671297,
    1046703,
    1053526,
    224396,
    2378928,
    80532,
    77496,
    2879467,
    969132,
    2812797,
    565860,
    994285,
    509362,
    2957038,
    2531131,
    2981837,
    397343,
    2645171,
    2392731,
    801676,
    17900,
    156666,
    1595929,
    2722389,
    2758209,
    107240,
    1635828,
    1630993,
    2436398,
    1250676,
    2864692,
    1606296,
    210359,
    2810255,
    2452117,
    318585,
    465723,
    234559,
    459956,
    650119,
    2964031,
    1634640,
    1387102,
    1117084,
    2813547,
    2680821,
    780624,
    385346,
    2657681,
    2417354,
    693818,
    1041744,
    1055252,
    2019960,
    2310287,
    468866,
    332752,
    2161832,
    135097,
    1212272,
    2226499,
    1044187,
    105309,
    2931981,
    2882533,
    470794,
    2104994,
    665469,
    2787772,
    447192,
    1441922,
    397305,
    2893258,
    1198536,
    1430396,
    218891,
    2320853,
    2952272,
    909056,
    2872478,
    562989,
    914207,
    517677,
    1770231,
    1688830,
    1124530,
    384808,
    851605,
    2294249,
    656141,
    230206,
    2594946,
    2862033,
    1343576,
    292285,
    1437384,
    2970573,
    1343556,
    426318,
    808116,
    493296,
    277247,
    1593590,
    350601,
    2758920,
    286249,
    2011989,
    343733,
    2902595,
    21428,
    1438608,
    2299496,
    1457256,
    2911610,
    2531727,
    643733,
    1373181,
    255772,
    285119,
    1335111,
    1670292,
    461241,
    547956,
    1398888,
    1547018,
    1426138,
    2547033,
    2319760,
    1623705,
    280977,
    2418653,
    2512722,
    207592,
    2832934,
    440152,
    1618367,
    2236458,
    71845,
    566618,
    2418895,
    99967,
    2867128,
    793919,
    2775888,
    2378505,
    1413409,
    2226474,
    525649,
    1456329,
    2874005,
    1788957,
    1625480,
    1245827,
    1937592,
    475154,
    654356,
    2866119,
    27884,
    622551,
    73460,
    956288,
    693,
    224617,
    2667982,
    2534495,
    2909256,
    1406110,
    138143,
    977763,
    2212072,
    17216,
    216059,
    487843,
    996702,
    1038870,
    2850744
]

selected_conversations = amazon_df[
    amazon_df["conversation_id"].isin(
        selected_conversation_ids
    )
].copy()


# ------------------------------------------------------------
# 3. Sort conversations chronologically
# ------------------------------------------------------------

selected_conversations = selected_conversations.sort_values(
    ["conversation_id", "created_at"]
)

In [17]:
def show_conversation(conversation_id):

    conversation = selected_conversations[
        selected_conversations["conversation_id"] == conversation_id
    ]

    print("\n")
    print("=" * 100)
    print(f"CONVERSATION: {conversation_id}")
    print("=" * 100)

    if conversation.empty:
        print("⚠️ Conversation not found.")
        return

    for _, row in conversation.iterrows():

        role = (
            "👤 Customer"
            if row["inbound"]
            else "🏢 AmazonHelp"
        )

        print(f"\n{role}")
        print("-" * 80)
        print(row["clean_text"])

In [ ]:
#Vidhul
show_conversation(863820)
show_conversation(525543)
show_conversation(1231224)
show_conversation(2841686)
show_conversation(2369649)

====================================================================================================
CONVERSATION: 930181
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Recently moved from Kindle Voyage to Kindle Oasis. Wiped and sold the Voyage, and then realized that my notes weren’t brought over. I thought those were saved to the cloud somewhere. Am I out of luck? Any way to retrieve them from old/wiped device?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thanks for contacting us today! We'd like to help if we can! To confirm, are you seeing your notes listed here: but not on the device? ^CS

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp That is correct. I am seeing them on that site. Both the ones on the Voyage, and the couple I’ve done on the Oasis, but on the Oasis, only seeing the ones made on that device.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Here's a link to our Help page with info on bookmarks, highlights, and notes: Please let us know if this doesn't solve the issue for you. ^BV

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp That just seems to tell me how to create new ones, that page doesn’t all seem relevant to the conversation previous to when ^BV replied. Whoever ^CS was seems to have figured it out.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] The link provided by ^BV gives info on how to view your notes and highlights. Underneath each section about adding items, we'll also include instructions for viewing. When you try the "View" instructions, are you able to view your notes and highlights? ^WT

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp To be clear, I want to view them on my KINDLE, not on the website. How do I get them down to the Kindle again?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We'd be happy to do some live troubleshooting with you, if you'll please phone us here: Please keep us posted! ^LB

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I don’t have time for phone call - there’s no way to get the old highlights/clippings (from previous Kindle) down from the website to my current kindle? Doesn’t seem to be a way to get them down from website to my new Kindle.


====================================================================================================
CONVERSATION: 1132075
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
hi @AmazonHelp twitter rejected my report of the fraud account @ AmazoncHeIps (who are demanding my amazon login details) maybe you can try?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I didn't want to tag them even though I blocked them and now they blocked me, but I don't want people to fall for it and give over details

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Jay, we'll make sure to get this reported on our end. Thanks for letting us know. ^EM

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp No prob. Twitter support notified me there was "no violation" but hopefully if you claim it as company they may listen!


====================================================================================================
CONVERSATION: 1551751
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Hi, where can a Createspace/KDP author learn online about getting his books into an Amazon bookstore in his home town?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thanks for the interest! Let's explore your options with Kindle Direct Publishing here: ^SH

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp You didn’t even read my question, did you? I’ve got 4 books already in KDP. This is about the physical store. #BotFail


====================================================================================================
CONVERSATION: 346732
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] [USER] and since then no information. No texts or calls on it's status. No details of courier boy shared. Finally I call 2 of 3

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry for the trouble. Could you let us know the delivery date quoted for the order? ^GK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp It was yesterday October 7, 2017. Today I get their first text saying "delivery failed" Not done bro. Not done. Sort it out quickly


====================================================================================================
CONVERSATION: 1447950
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Hey @AmazonHelp once again my package is delayed. 3rd time in a row. Is prime really worth it if my packages never get here in 2 days??

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm so sorry for the wait! Do the orders have the same carrier in common? If so, who is it? ^MH

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp They do not have the same Carrier. It’s happened occasionally throughout the years but it’s happening all the time now.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry for the troubles! Have you discussed these issues with the carriers directly? ^TK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Yes. They said they’ll deliver when they can. I live about an hour north of your biggest hub and can’t get packages delivered timely!

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We'd like to look into these issues with you via phone, here: Please keep us posted! ^LB

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I want you to see the tracking information. This is ridiculous!

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry for this poor experience! Please reach us directly by choosing "phone" here: ^HS

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Still no package. Reached out to lasership and they said this morning. You should overnight my order so I have it tomorrow.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Going out of town on Sunday and needed items by then. Very upset with they way you are delivering now. Prime no longer worth the cost.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] What options did you receive when you contacted us using the link previously provided? ^DA


====================================================================================================
CONVERSATION: 863820
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] @AmazonHelp [USER] #WhyIWrite i want people to think 100times before buy with amazon, they made me cry like anything

👤 Customer
--------------------------------------------------------------------------------
[USER] @AmazonHelp [USER] For refund you make cutomer cry like this, send them desk to desk to beg

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I understand your concern. Please reply to the email you've received from our specialist team. They'll get back to you soon. ^HD

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please don't provide your order details, we consider it personal information. Our Twitter page is visible to public. ^HD

👤 Customer
--------------------------------------------------------------------------------
[USER] @AmazonHelp [USER] Everyday i am having call with amazon for 1hr pleading and begging to give my money back... and amazon just screams back “wait” #shame

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] From the screenshot shared earlier, I see that this issue has been escalated to the highest point of escalation. 1/2 ^HD

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please reply to the email you've received from the specialist team and they'll get back to you. 2/2 ^HD

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] what highest escalation point you talking about, they have never contacted after the mail

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] none of your team members are ready to help, they just slam the call on face with sorry

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] tweeting since 3days, even you guys neva responded. You made me beg for my money, never expected..

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We have responded to you via DM. Please check. ^SQ

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] Still people from amazon are asking me details of order which I explained them 20times This is how you guys kill the customer?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] This will be the last time shopping with amazon I am ant my money back from amazon which they have not initiated yet

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Apologies for the bad experience with the refund of the order. As mentioned earlier, ^AK (1/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] kindly reply to the email sent by our specialist team and they'll get in touch with you soon. Appreciate your patience. ^AK 2/2

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] Amazon team without even understanding the issue are replying me back Please know the facts first All ur executives slammed ph on my face.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] @AmazonHelp [USER] [USER] [USER] i have been calling amazon and requesting them to call me back, but all slammed the phone on my face

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @AmazonHelp [USER] [USER] [USER] i have been calling amazon and requesting them to call me back, but all slammed the phone on my face

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @AmazonHelp [USER] [USER] [USER] i have emailed them with all the bills, but still you guys are not ready help customer

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @AmazonHelp [USER] [USER] [USER] i would really request people to see this tweet chain, to see how bad they behave with customer.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @AmazonHelp [USER] [USER] [USER] [USER] with out even knowing the facts amazon is replying to me.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] team, they will reach out to you. (2/2) ^GK

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I get your disappointment. Once you write back to the email you've received from our specialist (1/2) ^GK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] #AForcaDoQuererFinal i want people to help me retweeting this tweet, as amazon and his ceo is jot ready to help and want me to beg them.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] Even the ceo of the company is enjoying seeing the customer beg to him for his own money.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] This will by last time shopping with amazon, really appreciate how amazon and his team behaves in worst manner possible with the customer

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] Enough how amazon is making me cry for my money I want people to support me now #AForcaDoAQuererfinal #ShowtimeLetsCelebr8

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] Shame on amazon, despite tweeting and requesting these guys are not even contacting the customer

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] See how attitude they have, they are even ready to make the customers cry, and the ceo is enjoying this

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] see hoe amazon is bot responding atall now My worst ever shopping with amazon [USER] [USER]

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] Amazon is just torturing like anything me, for my money, i keep on plead them they keep on slamming the ph on my face

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Hello Akshay, I assure you, our team is working on your concern and will get back to you with an update on priority. ^RS

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] amazon is giving me mental torture now😭😭, no specialist from amazon called me or helped me in issue

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] your concern, kindly pick their correspondence and reply for updates &amp; further assistance. 2/2 ^MJ

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry for the poor experience lately, our executive customer relations team wrote an email with regard to 1/2 ^MJ

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] Are you guys working in sleep, i did not get any call or mail ok, which concern team your talking about. See the way your talking to me

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] Is this the way you talk to your customer, without even checking the details you are coming and givig this statement

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] Again marking it in bold “none of your customer executive contacted me”

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] You guys are just torturing me to the hell, mentally i am getting tortured by amazon

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] When will you intiate my refund? When will your customer executive call me? When will your highest escalation team call me?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Sorry for the mess. Please drop in your details here: I'll look into the issue for you. ^ST

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] No body from the amazon team is ready help again marking with bold “24hours have passed no body contacted”

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] I have dropped a mail to ceo desk to but nobody contacted

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] #AForçaDoQuererFinal #ShowtimeOctoBest #TwitterIn4Words #ALDUBxEBLoveis amazon is not ready to call and help me atall for my refund

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I understand your concern. Request you to wait while the team works on your issue and get back to you. ^ST

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] [USER] See the way amazon speaks, so rude. Is this the way you deal with your customer? #AForçaDoQuererFinal #ShowtimeLetsCelebr8 #TwitterIn4words

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry that you have not received a callback, we have been requesting to fill in 1/2 ^MJ

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] your details in the secured link to help. Appreciate your understanding. 2/2 ^MJ

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @AmazonHelp [USER] [USER] [USER] [USER] [USER] #TwitterIn4words what happened? I gave my details to you right? Now what?

👤 Customer
--------------------------------------------------------------------------------

In [31]:
import pandas as pd

# ============================================================
# 1. Create complete conversation text
# ============================================================

def build_conversation_text(group):

    messages = []

    for _, row in group.iterrows():

        # Identify speaker
        if row["inbound"] == True:
            role = "Customer"
        else:
            role = "AmazonHelp"

        # Get cleaned message
        text = row["clean_text"]

        messages.append(
            f"{role}: {text}"
        )

    # Join all messages into one conversation
    return "\n\n".join(messages)


# ============================================================
# 2. Build complete text for every conversation
# ============================================================

conversation_texts = (
    amazon_df
    .groupby("conversation_id", sort=False)
    .apply(build_conversation_text)
    .reset_index(name="conversation_text")
)


# ============================================================
# 3. Update the Golden Set
# ============================================================

# Remove the old incomplete conversation_text
golden_set = golden_set.drop(
    columns=["conversation_text"],
    errors="ignore"
)


# Add the complete conversation text
golden_set = golden_set.merge(
    conversation_texts,
    on="conversation_id",
    how="left"
)


# ============================================================
# 4. Arrange columns
# ============================================================

golden_set = golden_set[
    [
        "conversation_id",
        "conversation_text",
        "candidate_intent",
        "candidate_count",
        "group",
        "sampling_type",
        "gold_intent",
        "label_reason",
        "difficulty"
    ]
]


# ============================================================
# 5. Check the result
# ============================================================

print("Golden Set shape:", golden_set.shape)

print(
    "Missing conversation texts:",
    golden_set["conversation_text"].isna().sum()
)

print("\nExample conversation:")
print(golden_set.iloc[0]["conversation_text"])

Golden Set shape: (192, 9)
Missing conversation texts: 0

Example conversation:
Customer: [USER] thanks for the gift card that was unusable. $50 someone wasted 😠

AmazonHelp: [USER] Oh no! We'd like to help if we can Brian! Please contact us via phone or chat here: ^AJ

Customer: @AmazonHelp They escalated and in minutes I had my balance in my account, great service!!!

C:\Users\Nihelesh M U\AppData\Local\Temp\ipykernel_7172\2285066971.py:37: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(build_conversation_text)

In [33]:
# ============================================================
# 6. Save updated Golden Set
# ============================================================

golden_set.to_csv(
    "../data/processed/amazonhelp_golden_set.csv",
    index=False
)

print("✅ amazonhelp_golden_set.csv updated successfully.")

✅ amazonhelp_golden_set.csv updated successfully.

In [35]:
#Mani
show_conversation(1699857)
show_conversation(2283867)
show_conversation(2408704)
show_conversation(671297)
show_conversation(1046703)

====================================================================================================
CONVERSATION: 1699857
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] No response to my return order for Omega 369 soft gels. expiry too near. Order ID: 406-2352573-1531566 Seller: Health-Mall

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Sorry for the hassle. Please report this to our support team here: and we'll check this. 1/2^HN

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please don’t provide your order details as it is personal information. Our page is visible to the public.2/2^HN

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp ok


====================================================================================================
CONVERSATION: 2283867
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] @AmazonHelp utterly disgusting customer service. I ordered my Grandsons main birthday present in plenty time for his birthday. And yet it still hasn't arrived for his 1st B/day today, even though it was due to be delivered yesterday. What's the point in prime service?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry you didn't receive your order when you expected! I understand how frustrating that is! We'd like to help! Please reach out to us via phone/chat here: and we can provide further assistance. ^TK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I've phoned several time and still I'm no further forward.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] When you reached out to us through the previously provided link, what information was provided? ^RR

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp The advice was to call Amazon.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We'd still like to assist. What options or insight were we able to provide when you spoke with us? ^SJ

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp They were pointless. I'm waiting a few days to see if the refund will actually arrive in my bank account. If it's not (As advised by my bank) they will look into outing a fraud claim in.


====================================================================================================
CONVERSATION: 2408704
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Das erste und letzte mal Festplatten bei [USER] bestellt - aus Zeitgründen. So kamen sie jedenfalls an. Nahezu unverpackt, ungeschützt und vor allem in einem viel zu großen Paket. 😡 (So verpackt man vielleicht Plastikspielzeug, aber keine 900 €.)

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Oje! So sollte das nicht bei dir ankommen. Ist denn der Inhalt heil geblieben? Falls nicht, kontaktiere bitte unsere Kollegen im Kundenservice: Gerne kannst du uns auch hier Feedback zur Verpackung geben: ^SK


====================================================================================================
CONVERSATION: 671297
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Has anyone used their Amazon Prime lately and not had a late package?? I feel like late is their normal anymore. I ordered some little baby boots for Elliott’s first thanksgiving outfit and they’re not going to arrive on time. 😭🤬 @AmazonHelp

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry to hear your order is late! What is the current tracking status for the order? You can review this information here: ^JS

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I was sitting at my house waiting on my package, that was supposed to be delivered yesterday, and just got this notification from USPS. No one attempted to deliever. I had my windows open watching for them

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thanks for the info! We'd love to connect you to USPS to submit feedback. Please feel free to reach out to us here: ^SH


====================================================================================================
CONVERSATION: 1046703
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Time to make your delivery executive famous! Absolutely arrogant, rescheduled the delivery without contacting me, cancelled the order when specifically asked to deliver it the next day. Maybe you should do something about this. I want my product delivered today! 😑😤

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We'd like to investigate this, please share your details here: ^HA

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Check the feedback on the link.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I get the concern, however, we'd like to check what went wrong. Please share the details and we'll reach out to you. ^MS

In [ ]:
#Sabarish
show_conversation(1053526)
show_conversation(224396)
show_conversation(2378928)
show_conversation(80532)

====================================================================================================
CONVERSATION: 1053526
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Freaking service by Amazon!!! One of the waste online sites ever seen [USER] @AmazonHelp

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Looks like you had a bad experience with us. Please tell us what went wrong, we will help you. ^BS

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp U people cancel the order by ur choice n then ask us to place a new order wen there is hike in price

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] You should've received one too about this. I've shared your feedback with the concerned team for review. [2/2] ^HA

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry about the order being canceled. Every canceled order is followed by an email with the reason. [1/2] ^HA

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Wen u guys can't be up with ur words n y the hell do u guys publish ki u give offers n all

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp My order was cancelled cz it was damaged in transit n wen I asked for order ur cs team is saying I have to place new order

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp If u guys decide wthr to deliver the order o not then y the fuck u guys have started online shopping to satisfy custmr o to fuck them?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Apologies for the ordeal. Since the package is damaged in transit, it can't be delivered to you. ^VN (1/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] If you'd like, kindly place a new order and we'll ensure the delivery. Appreciate your understanding. ^VN (2/2)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I'll place a new order can u guys deliver my order for the same price which u gave me B4??

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] order for the price mentioned on the website as it is the best price we could offer you. (2/2) ^VR

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I understand your concern, unfortunately we do not have price match policy. I request you to kindly place a new(1/2) ^VR

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp U people r crazy really u want me to pay 2k more for that same fuckin order so that u guys could damage it once again

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Further, I'll surely forward this as feedback internally and we'll work on it. (2/2) ^RI

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I understand your concern. As stated earlier, we'll not be able to reinstate the order. (1/2) ^RI

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Wat the fuck can you do?? Ur jus testing my patience U guys r cheat fraud cheating in the name of sale fuck u guys n goodbye to Amazon

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp U will work internally wat the fuck I will do with that?? I want my product that to in discounted rate

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please don't provide your email address, as we consider it to be personal info. Our page is visible to the public. 2/2 ^OS

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] That's strange! We'd be glad to help you. Please contact our support team here: 1/2 ^OS

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp If u guys have lil bit of shame n pride then call me 8884928125

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please don't provide your details, we consider it to be personal information. Our page is visible to the public.(2/2) ^VR

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We'll not be able to reach you from here, kindly reach us from the link shared so that we can assist you. (1/2)^VR

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Ur cs team is not able to find my details even after giving all info the person who spoke with me called Satish couldn't fetch my details

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Ur supervisor ur managers are all afraid to take call wen I ask for call transfer those people hide.😂😂


====================================================================================================
CONVERSATION: 224396
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] hey when is next Young Sheldon episode available in India.

👤 Customer
--------------------------------------------------------------------------------
[USER] We do not have any announcement for this as of now. Please stay tuned for any update. ^SG

👤 Customer
--------------------------------------------------------------------------------
[USER] Ok, keep me posted. Pls add Dr. Rajendra Prasad Telugu movies from 90's. Thank you.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thank you for the suggestion. I shall definitely forward your feedback regarding this to the concerned team. ^HR


====================================================================================================
CONVERSATION: 2378928
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
My last 2 Amazon orders somehow got delayed then lost by the delivery driver &amp; had to be refunded. Amazon has never been this terrible.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry to hear that your delivery experience with us was less than pleasant. When was your order scheduled to be delivered? You can check here: ^SY


====================================================================================================
CONVERSATION: 80532
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] cheats people, I paid 8999 from my Amazon Pay for a mobile, balance deducted but order cancelled, when I contacted, no help. It's a simple fraud, I am going to sue Amazon India

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We would like to help you. Please share your details with us here: We'll get in touch shortly. ^CB

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I am contacting Amazon since 28/11/2107 but no one helps me. I purchased a mobile on the said date, my Amazon Pay balance deducted but order cancelled, I am still waiting for refund

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I understand you're disappointed, Asif. I apologize about the experience you had with this order so far. We'd like to assist you. Kindly share your details through the link that was provided earlier so that we can take necessary action from our end. ^NK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp OK, I am going use the link but your apology doesn't qualify here, I need my order completed. Why should I pay you more for the same product for no fault of mine.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We would our best to make things right for you. Once we have your details with us, we'll work on it right away. ^CB

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I have used the link provided by you and sent the details, now do whatever but I want my order completed, how dare you people try to cheat customers in broad day light. I have Amazon Pay screenshots with me.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thank you for sharing your details. We'll work on it and get back to you with an update via email soon. ^NR

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp How this order got cancelled for 'payment declined' reason where my Amazon Pay Balance was 9300 (2500 in money &amp; 6800 in Gifts and Credit )at the time of order and 8999 was deducted? Even no refund made till now for Gifts &amp; Credit money (Rs. 6800). It's simple fraud by Amazon.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Do you people know the meaning of 'soon'? I am contacting Amazon since 28/11/2107. Still you people claiming soon. It's pathetic. No CCE helps me when I tried to express my concerns. I have all the evidences in the form of Amazon Pay Balance Account Statement screenshots.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] In this case, it seems your bank delayed in sending the approval or the funds were stuck at their gateway. The charges you're referring is just an authorization which can't be claimed by Amazon.in merchant. ^NR 2/3

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Sorry to know the payment was declined. When you place an order Amazon tries to charge the amount on your payment method. There is a certain time frame in which we require approval from your issuing bank. ^NR 1/3

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] If debited, they'll be refunded back to you by your bank itself within 2-4 business days. Please feel free to revise the payment if you are getting a prompt for it so that the order can be placed. ^NR 3/3

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Do you understand English? How come question of a bank arise? I have paid with Amazon Pay Balance yes you heard it right Amazon Pay Balance. Is this what you offer as help?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Did I ask for any charges? Do you understand what you write?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp What the hell is this? How come a bank comes into the picture where I paid the whole amount from my Amazon Pay Balance? Make yourself aware about your own Amazon Pay Balance otherwise you can't help anyone.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry about the previous Tweet, we would like to know your concern in detail. Write to us here: &amp; we'll take necessary actions to make things right. ^MJ

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] To assist you regarding this in a better way, please connect with us here: ^NR

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I have sent you the details. There is no question of refund now, I want my order completed. Get it?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thanks for sharing your details, appreciate your patience while we help you with the available options. ^MJ

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I am still waiting for help. How come my balance deducted and it's not there in Amazon Pay Balance Account Statement? It's simple cheat from Amazon India.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] You must've received a correspondence from us on this. Please find it, here: and kindly revert to it if needed. ^YP

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp What should I do with your correspondence? I need resolution but Amazon people cheating us. I have sent all the details but in vain. It's 6 days now and Amazon is not even responding, I have to call them, pathetic!

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] If you are not happy with the resolution provided in the correspondence, you may reply to the mail with your insight on this and we'll assist you further. ^VH

In [40]:
#Siva
show_conversation(77496)
show_conversation(2879467)
show_conversation(969132)
show_conversation(2812797)

====================================================================================================
CONVERSATION: 77496
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] this is ridiculous...i specified that this order was a gift too....and a "replacement" would cost me more since one of the items was a part of a lightning deal...

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Hi, have you had a chance to request a refund or replacement for your order?^PJ

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp not yet, would a replacement still be of the same amount if one of the items was a part of a lightning deal?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Great question! Please reach out to us here: so we can look into this together. ^SC

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp ok but this is a link to the UK site and i live in the US

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Apologies for the incorrect link, Hannah. You can get in touch here: ^TI


====================================================================================================
CONVERSATION: 2879467
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Ordered Lenovo Z2 Plus for the second time from [USER] and again they cancelled it on the day of delivering. Order# 406-1020722-6875566 Tracking# 447207503857 So much hype for your service? which is absolutely horse crap!!!

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry that your order is canceled. Kindly reach out to us here: and we'll check it for you. Please don't provide your order details, as we consider it to be personal information. Our Twitter page is visible to the public. ^AU

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp and what thats gonna do? already spoke to your rep and they said they cant do anything, and a month has been wasted, already placed and got cancelled twice, tell me if you can do anything

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp i gave my office address for delivery and been waiting here for 2 hours after shift, only to find out its "undeliverable" why post the order if you cant deliver it?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp [USER] Wow good services 😒

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I can understand how upsetting it can be when an order is canceled. We'd like to work on this. Kindly share your details here: - and we'll get back to you at the earliest. ^SC

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp spoke to your support, all they could do is refund the amount. Are you guys serious? Your courier guy didnt even call me once and rejected my exchange, you have wasted 1 month for me, i'd rather go to the consumer court now

👤 Customer
--------------------------------------------------------------------------------
[USER] @AmazonHelp their courier guy rejected the order without even calling, and this is the second time, just blanked 😡

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We'd like to take a closer look at the issue. Kindly drop your details through the secure link above and we'll get in touch with you. ^NS


====================================================================================================
CONVERSATION: 969132
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] [USER] [USER] Amazon is Gang of THUGS &amp; most CORRUPTED CHOR online portal delivering duplicate, defective and 1st copy items.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry the issue hasn't been resolved yet. Please reply to the email received from us and we'll get back to you. ^SH

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Shut up Bunch of Liars. Refund my money right now. MOST CORRUPTED customer care on this earth

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] As this is a social media platform, we can't view your account/order details. (1/2)^HR

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Hence, please reply to the email you have received and we will get back to you with an update.(2/2)^HR


====================================================================================================
CONVERSATION: 2812797
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Nice delivery. #Amazon Really, top of my driveway #horribledelivery

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry your package was delivered in this manner! We're here to help. Please let me know who the carrier is, found here: ^SE

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp The tracking number was TBA569724726000

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] For your account security, please do not post account information like the tracking number on Twitter. Someone from my team would like to escalate this experience with you. Please provide all the details you can about the issue here: ^AJ

In [ ]:

show_conversation(565860)
show_conversation(994285)
show_conversation(509362)
show_conversation(2957038)

In [38]:
show_conversation(2531131)
show_conversation(2981837)
show_conversation(397343)
show_conversation(2645171)
show_conversation(2392731)
show_conversation(801676)

====================================================================================================
CONVERSATION: 2531131
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
本日も警戒船午前で終了 ウチに帰ると再度購入 アマゾンのFire TV Stickが 届いました。 プライム会員なので見放題 ビリギャル観たけど画像良し👍

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] ご購入、ありがとうございました。プライムビデオのコンテンツをぜひお楽しみください(*'▽') EK


====================================================================================================
CONVERSATION: 2981837
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
I give up. I've just updated my bank details TWICE on amazon and it just keep saying I haven't provided all information and sends me back to the start. Fuck it. I guess I'm not self publishing after all.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp ama [USER]

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry for the technical difficulties! Please connect with Kindle Direct Publishing here: The availability is 6 a.m. to 5 p.m. Pacific time, Monday - Friday. ^SH


====================================================================================================
CONVERSATION: 397343
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Apesar da linda atualização do app do Kindle, fiquei mais perdida que cego em tiroteio. 😁😊📚 [USER] [USER] #ebooks #Kindle

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Oi Carmeane, você precisa de alguma assistência? ^LG

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Não, não. Apenas acostumada com o antigo layout, kkkk. Mas agradeço a atenção. 😊😘

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Entendi 😅 Caso tiver alguma dúvida é só perguntar, Carmeane. Abraço! ^LG

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Agradeço novamente e parabéns ficou lindo o novo layout!! 😘👏📚

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Agradecemos o feedback 😄 Tomara que tenha um ótimo dia! ^LG


====================================================================================================
CONVERSATION: 2645171
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
iPhoneってKindleの購入出来ないの

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] 恐れ入りますが、Apple社の定めるポリシーにより、Kindle for iOSアプリから直接Kindle本をご注文いただくことができません。お手数ですが、ブラウザよりストアにアクセスし、ご注文ください。 RI


====================================================================================================
CONVERSATION: 2392731
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
You may as well just take all of my money [USER] - you know I'm going to want a few Amazon Echo Buttons now! 😍 #IrresistibleTech [USER]

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We love that you love it, go on... treat yourself! ;-) ^BD

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I fully intend to 😉 do you know when they’ll be available?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] No dates confirmed yet, Anna, but you can register to be notified of the release details here: We hope you enjoy them when they arrive! 😘 ^PJ

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Am already registered for updates 😁


====================================================================================================
CONVERSATION: 801676
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] your customer care team is not give a any information about this product . And not provide courier delivery details.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Sorry for the delay, Chandan. Kindly fill in your details here: and we will get back to you. ^KS

In [ ]:
show_conversation(17900)
show_conversation(156666)
show_conversation(1595929)
show_conversation(2722389)
show_conversation(2758209)

In [ ]:
show_conversation(107240)
show_conversation(1635828)
show_conversation(1630993)
show_conversation(2436398)
show_conversation(1250676)

In [ ]:
show_conversation(2864692)
show_conversation(1606296)
show_conversation(210359)
show_conversation(2810255)
show_conversation(2452117)

In [ ]:
show_conversation(318585)
show_conversation(465723)
show_conversation(234559)
show_conversation(459956)
show_conversation(650119)

In [ ]:
show_conversation(2964031)
show_conversation(1634640)
show_conversation(1387102)
show_conversation(1117084)
show_conversation(2813547)

In [ ]:
show_conversation(2680821)
show_conversation(780624)
show_conversation(385346)
show_conversation(2657681)
show_conversation(2417354)

In [ ]:
show_conversation(693818)
show_conversation(1041744)
show_conversation(1055252)
show_conversation(2019960)
show_conversation(2310287)

In [ ]:
show_conversation(468866)
show_conversation(332752)
show_conversation(2161832)
show_conversation(135097)
show_conversation(1212272)

In [ ]:
show_conversation(2226499)
show_conversation(1044187)
show_conversation(105309)
show_conversation(2931981)
show_conversation(2882533)
show_conversation(470794)

In [ ]:
show_conversation(2104994)
show_conversation(665469)
show_conversation(2787772)
show_conversation(447192)
show_conversation(1441922)

In [ ]:
show_conversation(397305)
show_conversation(2893258)
show_conversation(1198536)
show_conversation(1430396)
show_conversation(218891)

In [ ]:
show_conversation(2320853)
show_conversation(2952272)
show_conversation(909056)
show_conversation(2872478)
show_conversation(562989)

In [ ]:
show_conversation(914207)
show_conversation(517677)
show_conversation(1770231)
show_conversation(1688830)
show_conversation(1124530)

In [ ]:
show_conversation(384808)
show_conversation(851605)
show_conversation(2294249)
show_conversation(656141)
show_conversation(230206)

In [ ]:
show_conversation(2594946)
show_conversation(2862033)
show_conversation(1343576)
show_conversation(292285)
show_conversation(1437384)

In [ ]:
show_conversation(2970573)
show_conversation(1343556)
show_conversation(426318)
show_conversation(808116)
show_conversation(493296)

In [ ]:
show_conversation(277247)
show_conversation(1593590)
show_conversation(350601)
show_conversation(2758920)
show_conversation(286249)

In [ ]:
show_conversation(2011989)
show_conversation(343733)
show_conversation(2902595)
show_conversation(21428)
show_conversation(1438608)

In [ ]:
show_conversation(2299496)
show_conversation(1457256)
show_conversation(2911610)
show_conversation(2531727)
show_conversation(643733)

In [ ]:
show_conversation(1373181)
show_conversation(255772)
show_conversation(285119)
show_conversation(1335111)
show_conversation(1670292)
show_conversation(461241)
show_conversation(547956)
show_conversation(1398888)
show_conversation(1547018)
show_conversation(1426138)

In [ ]:
show_conversation(2547033)
show_conversation(2319760)
show_conversation(1623705)
show_conversation(280977)
show_conversation(2418653)

In [25]:
show_conversation(2512722)
show_conversation(207592)
show_conversation(2832934)
show_conversation(440152)
show_conversation(1618367)
show_conversation(2236458)

====================================================================================================
CONVERSATION: 2512722
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@119625 When will Mr. Robot Season 3 available for streaming?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@716115 We don't have the requested information. Kindly stay tuned for updates.


====================================================================================================
CONVERSATION: 207592
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115821 @115830 @AmazonHelp I wish just one of your agent would tell me the same story next time will go to @117249 cheaper and less hassle

🏢 AmazonHelp
--------------------------------------------------------------------------------
@139580 I'm sorry for the disappointment, David! Without including personal/account info, could you tell us more about what's wrong?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Amazon app says delivered at locker 1st amazon agent say not dispatched along with another and the last one says a bank issue yet

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @139580 I have said wt needs to be said on you mail ..dnt waste your time on me ..I am no more your customer ..goodbye

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp My online banking shows money taken, been told can't have refund due to item shipping , so if money issue why are you dispatching and

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp If it hasn't shipped yet why can't I cancel. They can say when it will ship or anything, so wasted time on phone wasted fuel going to pick

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp An order up that I was told was ready but wasn't, how can you screw a 6.99 order up so badly?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@139580 David, My team can look at this and get it solved for you. Just click the link and supply the details:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I'm not talking to anybody else , you can keep my 6.99 It's really not worth the hassle

🏢 AmazonHelp
--------------------------------------------------------------------------------
@139580 I'm sorry we've disappointed you. We're here to help. If you'd like us to look into this, please use the link EM provided.


====================================================================================================
CONVERSATION: 2832934
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Why thanks @115821 for your thoughtful packaging at this time of year, when you home deliver, to my home, in front of my 2 year old #UnlessYouAreGoingToDressLikeSantaPleaseUsePackaging #SantaIsMagic #WayToRuinChristmasAmazon #CantWaitForTheOthers #ConsideringCancelling

🏢 AmazonHelp
--------------------------------------------------------------------------------
@338075 Sorry for the frustration. Some items may be sent in manufacturer's box. If available for the item, you can mark "Ship in Amazon box" on the checkout page if you don't want to reveal the contents. More information can be found here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Thanks for your reply and info. When was things changed from boxes and how was this communicated with customers? I've been shopping on the amazon app for years and years (I'm unable to shop due to health reasons) and have not noticed this change or tick box.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I have gone through the order again and cannot see the option for this item please can you clarify as I want to see if I have missed this or it was not there when I complain and so far I cannot see it. Thank you


====================================================================================================
CONVERSATION: 440152
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Grabbed in #apptreasurehunt #AIFWSS18....it's my time now... Diwali begins ...thanks @115850

👤 Customer
--------------------------------------------------------------------------------
@219461 @115850 No treasurehunt today????

🏢 AmazonHelp
--------------------------------------------------------------------------------
@219460 We've got something more interesting "Festive riddles". Check out Amazon app for more.


====================================================================================================
CONVERSATION: 1618367
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115850 Your seller will refund only if I give a good review . Is this a amazon policy ?? Plz deal with such fraud seller

🏢 AmazonHelp
--------------------------------------------------------------------------------
@496194 That is unusual, Anish. Did you try reaching out to us via: in regard to this ?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Yes . Used the amazon app and received a reply from the sellers who asked me to give them a good rating aftr I get my refund. Can fwd u Emil

🏢 AmazonHelp
--------------------------------------------------------------------------------
@496194 We'd like to have a closer look at it. Write to us here: and we'll contact you soon.


====================================================================================================
CONVERSATION: 2236458
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Touche @115821, instead of throwing it over the fence you just didn't deliver it. Did not see that coming. Hard to be mad, I kind of have to respect it.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@277610 I'm sorry it hasn't arrived. Does the tracking show it as delivered:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp No, I got a message saying it was undeliverable, and now your guy is making me place my order again while you refund it. Amateur hour right now

In [24]:
show_conversation(71845)
show_conversation(566618)
show_conversation(2418895)
show_conversation(99967)
show_conversation(2867128)

====================================================================================================
CONVERSATION: 71845
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115830 been trying to login to my account to place an order, but it won’t let me! What’s going on?! #Irritating

🏢 AmazonHelp
--------------------------------------------------------------------------------
@132121 Hi Zoe, have you checked to make sure your username and password are correct? You could always try to choose the "forgot username/password" option and follow the instructions from there.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I’ve already done this and changed my password and it still won’t log me in ‍️

🏢 AmazonHelp
--------------------------------------------------------------------------------
@132121 Sorry to hear this. Please reach out to us here: so we can look into this for you.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Ok thank you all done and sent.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@132121 Great, please keep us informed about this!


====================================================================================================
CONVERSATION: 566618
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp why is it taking so long to answer my messages on DM? getting frustrated and would just like help regarding my issue i’m having with an order cancellation/refund.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@252847 I'm sorry you never received our message, it looks like we did respond. Have you checked the e-mails sent by Amazon? If not, you can do so by clicking here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I got one reply from my first message and I messaged back to say that I had received NO emails. Since then, nobody has replied to further help me with my situation.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp To further expand on my issue, I had cancelled an accidental order (that was placed yesterday and had not yet been shipped) expecting confirmation of a refund but nothing has been sent to me.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@252847 This isn't the experience we want for our customers. Was the order palced on Amazon.ca or a different Amazon site?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp The order was placed on Amazon.ca

🏢 AmazonHelp
--------------------------------------------------------------------------------
@252847 You should be able to see any notification e-mails here: If not, we're happy to assist you directly via phone, chat, or e-mail, here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I finally got an email confirming the order cancellation. It said I would only be charged for items that have been shipped but the item I cancelled had not yet been shipped, so will I get a full refund back? Is there something else I need to do in order to get my refund?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@252847 We charge you for items only when they ship out. What you may be seeing is a bank authorization. More information on bank authorizations may be found on this Help page:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I’m sure my bank authorized the use of my card with amazon as I was able obviously place an order. The money for the order was taken out of my account as expected for any other order. What I’m asking is, after an order is cancelled - will I get a refund?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I understand if the refunded money takes about 3-5 business days to transfer back into my account, I just want to reassure that a refund will be given to me.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@252847 If the order did not enter the shipping process, your payment method was not charged. When an order is placed your bank will put an authorization for the amount of your order on your payment method. See more about them here:


====================================================================================================
CONVERSATION: 2418895
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115850 Not able to receive sms OTP for Amazon Pay. Attempted many time. Solution?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@694967 Could you please confirm if you're trying to use Amazon pay balance to place an order or trying to add money to your Amazon pay balance?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Trying to add money, it asks me to add a phone no first.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@694967 Yes, you need to add your mobile number first to which an OTP will be sent during the payment. As you said you're not receiving the OTP, please help us with the error message you're encountering so that we can look into the issue.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp It says, OTP has been sent, but I never received on my mobile even after 2 hrs wait. I can DM you my login-id/mobile.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@694967 Please check if you have added the correct number or you're checking on the same phone number that you have added.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Great question KK. It is the same! how can reach to India support?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@694967 Please connect with our support team here: and they'll assist you regarding this.


====================================================================================================
CONVERSATION: 99967
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp ordered some samples from you. package was damaged and returned. i'd like to reorder the samples but the site won't let me since i technically already ordered the samples. help?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@137891 I'm sorry for the trouble with your order. We'd like a chance to take a better look at this with you. Please reach out to us via phone or chat here:


====================================================================================================
CONVERSATION: 2867128
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
It’s about time I gave this series another shot.

👤 Customer
--------------------------------------------------------------------------------
Oh, for goodness sakes. Hey @AmazonHelp, should I just send this back and get a replacement?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@165002 I'm so sorry your Blu-ray arrived damaged! Yes, you can see refund and replacement options here:

In [23]:
show_conversation(793919)
show_conversation(2775888)
show_conversation(2378505)
show_conversation(1413409)
show_conversation(2226474)
show_conversation(525649)

====================================================================================================
CONVERSATION: 793919
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Hey @115821 all the books I've ever ordered where damaged during delivery. I'm starting to get a bit pissed off about it.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@309299 I'm sorry your items were damaged. You can view your options here:


====================================================================================================
CONVERSATION: 2775888
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115830 @116324 Is this your new delivery method? #anywherewilldo #newlaptopthrownovergate

🏢 AmazonHelp
--------------------------------------------------------------------------------
@775646 I'm so sorry for this poor experience, Jenni! Is the laptop okay?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Seems to be thankfully. Outer box damaged but inner one seems ok. Haven't turned it on yet as it's a christmas present

🏢 AmazonHelp
--------------------------------------------------------------------------------
@775646 Glad the inner box was undamaged


====================================================================================================
CONVERSATION: 2378505
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Purchased something from @115850 and can't get GST because there is no option while placing order and they refuse to change the bill @137848 #FAIL #DigitalIndia #GSThelpdesk

🏢 AmazonHelp
--------------------------------------------------------------------------------
@685941 I'm afraid that invoices generated once cannot be changed. However, please reach out to our support team here: for further assistance. Dheeraj | Amazon Customer Service

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp We are also in business. GST returns not filled invoice can be modified and when I ordered immediately mailed in few hours about this prob not after delivery.sad to know this kind of response

🏢 AmazonHelp
--------------------------------------------------------------------------------
@685941 I understand your concern. Please fill in your details here: and we’ll contact you soon.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp No response on the return of the product yet

🏢 AmazonHelp
--------------------------------------------------------------------------------
@685941 As you have filled in the details, you will receive an email communication here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Pick up was due on 13th nov but no response from the retune team

🏢 AmazonHelp
--------------------------------------------------------------------------------
@685941 I'm afraid we haven't received your details. Please sign in to your account, and send us the details using the link provided by 'MN' here: and I will look into the issue right away.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp What details return pick up was scheduled for 13th nov but no one came to pick up

🏢 AmazonHelp
--------------------------------------------------------------------------------
@685941 I get your concern however, since Twitter is a social media platform, we'd not be able to check/access your account. Kindly share your details through the link provided earlier & we'll look into it right away. Appreciate your understanding.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 710404392068 pick up id

🏢 AmazonHelp
--------------------------------------------------------------------------------
@685941 As mentioned earlier, we can't gain access to your account details via Twitter. Kindly share your details in the link provided above by and we'll have the issue checked for you. (1/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@685941 Please don't provide your return tracking details, we consider it to be personal info. Our page is visible to the public. (2/2)


====================================================================================================
CONVERSATION: 1413409
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115850 @131027 @115851 @13150 @118341 Amazon.in Order # 407-3061248-5011532.Replacement not recd after returning the laptop.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 we'll fix this for you. Please don't provide your order details, we consider it to be personal information. (2/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 I'm sorry about the unpleasant experience, Manishaa. Kindly submit your details here: and(1/2)

👤 Customer
--------------------------------------------------------------------------------
@115850 @131027 @115851 @13150 @118341 amit das is a pick up boy n his no.8981867399 is switched off since pick up and nirmol system updater having also switched off 86200 23869

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 Have you filled in the form as requested earlier?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp yes i did it and i nid the investigation properly from ur end as i need justice its a big scam and i m victimised its all planned by ur kol

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 If you've shared your details in the link, you must've received a correspondence to your email id. Please check.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp i haven't recd any email till now pls help us to get justice as we had victimized by your Kolkata pick up hub team n pls look into the mater

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 Could you please check and confirm if you've received any correspondence from our side here: ?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp not yet...my mail id __email__

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.(2/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 We've received your details. We'll get back to you with an update at the earliest. (1/2)

👤 Customer
--------------------------------------------------------------------------------
@115850 @131027 @115851 @13150 @118341 Your return pickup for 407-3061248-5011532 is scheduled for today and will be picked up between 1:00PM-4:00PM by AmzAgent(7980833986).

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 Sorry for the trouble you've had.Kindly reply to the email you've received from our team & we'll look into this for you.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 Please don't provide your order details, as we consider it to be personal information. Our Twitter page is public.​

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp we have not recd any email

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 An email was sent to your registered account from Social media team. Please refer and revert on the same.

👤 Customer
--------------------------------------------------------------------------------
@115850 @131027 @115851 @13150 @118341 pls update that when can i get the replacement?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 This being a public platform, we wouldn't be able to check your order related info from here. (1/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 Hence, request you to reply to our email for further assistance. (2/2)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Arriving Today: Your package is out for delivery. i haven't recd the cont no.of delivery boy .i need identity card

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 We request you to wait till EOD for the package to be delivered to you soon.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp i havent recd the package n recd the message that delivered successfully.pls help us from fruads who r plotting here and playing with us.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp froggery going on its a big scam

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 we’ll contact you with an update.(2/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@448467 We'd like to take a closer look into this. Kindly fill in your details here: and (1/2)


====================================================================================================
CONVERSATION: 2226474
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Super excited to congratulate our India team for making Amazon.in the country’s leading shopping destination. #IndiaAllHands

👤 Customer
--------------------------------------------------------------------------------
@209576 Customer care of Amazon India is very unprofessional. No use. No return pick up may be problem with Blue Dart. Nobody is interested. Go thru FB page. Huge complain. Will be careful to deal with Amazon. Not expecting from this MNC. Very sorry state. Pl go indepth

🏢 AmazonHelp
--------------------------------------------------------------------------------
@649932 I'm sorry to know about the pending return. Kindly share your details here: and we'll help you.


====================================================================================================
CONVERSATION: 525649
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Ur Amazon india customer service is useless. Have been raising complain against old manufacturing date item supplied since 01Nov. All this while was told to wait and now being told return window shut. What kind of racket are your people running ? Lies & lies. Pathetic

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 That's unusual, we'd like to have a closer look into this. Please share your details here: and we'll assist you accordingly.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 1) What kind of dumbheads have been employed by Amazon. Order # 407-8065031-4709969. I have been calling & raising complain regarding 1 yr old product being delivered. Please check my calls from 01 Nov. Check my email dated 25 Nov with call records of same. Check ur email dated

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 2) 16 Nov and 26 Nov and all other emails since 01 Nov. What should a customer do when Amazon cheats by supplying 1 year old electronic item? Call and Raise complain. Your executives tell you not to worry as Amazon will take care of the issue. But it's a ploy to keep us waiting.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 3) So that window period closes and Amazon will shift the blame on customer. I think Amazon is hand in gloves with its seller partner and cheating customers by supplying one year old product. Shame on Amazon and really pathetic.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 4)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 5)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 6)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 7)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 8)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 9)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 Sorry for the inconvenience that this may have caused to you. If you had reported about the issue within the return window then we still consider the return. Drop in the details on the link here we'd check and connect with you. 1/2

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 Please don't provide your order details, we consider it to be personal information. Our page is visible to the public. 2/2

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I had already dropped in details previosly. And hence attached copy of emails. If you want copy of call records; I had sent them as well on email to customer service. Kindly go through my emails dated 16 Nov and 25 Nov.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 Thank you for sharing the details, we will get back with an update soon. Appreciate your cooperation.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Still Awaiting solution to my grievance. It's been two days and now Amazon will say It's been over a month since delivery so can help even though I have been raising the issue since 01 November 2017.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 I had checked for the details but could not find any, I would request you to kindly drop the details once again on the same link that was shared earlier.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Why don't you go through my emails dated 16 Nov 2017 and 25 Nov 2017 wh8ch gives out all the details.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 Twitter being a social platform we will not be able to access your Amazon account. As informed earlier, please drop your details in the secure link provided to you previously.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp So don't you have access to Amazon Customer service to retrieve mails and correspondences to verify the customer grievance. Anyways I shall do the needful again.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 As informed earlier, we wouldn't be able to access your account on Twitter. Hence, we're requesting you to drop your details in the link shared to you previously. Appreciate your understanding.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Does ur cust care even cares abt customer? Do de read & understand basic English or U just employ donkeys 4 cheap labour & no brains? I'm writing dat I hv contacted multiple times after receipt of product & I get 1 standard copy paste response that it's past 10 days of delivery.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 The resolution provided over e-mail is the best we're able to offer at this point of time.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp How do you rank that solution to be best? I need email is of some one responsible. Your email is simply a copy paste job. I have been raising complain since 01 November but that doesn't ring a bell in you ears. Post Numerous phone calls and emails you are telling that no return

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp 2) is possible after 10 days. But I started raising complain since 01 Nov that was just 3 days after delivery. Why did your executives lie over the phone? Is that the business ethics of Amazon? Why was I told not to worry as Amazon is there to take care of customer?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 As the return window for the product has expired we request you to contact the manufacturer. Please proceed as per the resolution provided in the email. For further assistance, please reply to the correspondence.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp But how did return window expired ? Is it my fault ? I raised complain on 01 November and product was delivered on 28 October 2017. Y did your executives lied 2 me that return pickup has been generated? Y did you executives told me that it's Amazon will take care of return issue?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp And what will manufacturer do when seller is selling old products? Manufacturer will say that I must contact seller. You just want me troubled

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 All after sales services are handled by the manufacturer. More info Request you to get in touch with the support team of the manufacturer and escalate the details. They're the right ones to approach for assistance on the issue.(1/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@241603 If they denied honouring the warranty, kindly help us with a warranty/service denial certificate so that we can look into this and assist you accordingly. Appreciate your understanding. (2/2)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp To hell with warranty; I have not yet opened the product. My issue is I ordered car air purifier on Oct 25th 2017. I expect a product with couple of months old manufacturing date and not one year old. And that's the reason I have been complaining since 01 November 2017.

👤 Customer
--------------------------------------------------------------------------------

In [21]:
show_conversation(1456329)
show_conversation(2874005)
show_conversation(1788957)
show_conversation(1625480)
show_conversation(1245827)

====================================================================================================
CONVERSATION: 1456329
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp suspicious email telling me I've signed up to Amazon prime annual membership link to cancel takes me to PayPal account details

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @AmazonHelp I forwarded to __email__ the email address isn't but at first glance looks like it is

🏢 AmazonHelp
--------------------------------------------------------------------------------
@458022 Thank you so much for taking the time to do that, Charlotte!


====================================================================================================
CONVERSATION: 2874005
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Phishing email from __email__

🏢 AmazonHelp
--------------------------------------------------------------------------------
@797896 Danke für die Info. Bitte gleich löschen! Liebe Grüße und einen schönen Tag

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp kein problem. vielleicht könntetn ihr ja eine rundmail schreiben oder an eien nwsseite weiterleiten, damit niemand drauf reinfällt. gibt immer wieder leute die darauf reinfallen :)

🏢 AmazonHelp
--------------------------------------------------------------------------------
@797896 Danke :-) Noch ein Tipp für ggf. zukünftige Fälle: Gruß


====================================================================================================
CONVERSATION: 1788957
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
90% sure there’s someone pretending to be @115993 sending me emails to stop me account from being suspended

👤 Customer
--------------------------------------------------------------------------------
@537379 @115993 I got the same thing just with amazon and there telling me to input my card details and all otherwise there charging me amazon prime

👤 Customer
--------------------------------------------------------------------------------
@537378 @115993 Learn to spell

👤 Customer
--------------------------------------------------------------------------------
@537379 @115993 When you click the link mine asks me for all my address and bank details

👤 Customer
--------------------------------------------------------------------------------
@537378 @115993 The email address for “PayPal” wasn’t even a pay pal one and then it took me through 3 websites before loading to pay pal nah dodgy

🏢 AmazonHelp
--------------------------------------------------------------------------------
@537379 Hello! I'm sorry to hear that you're getting these emails. Upon review, this does not appear to be an email from ...

👤 Customer
--------------------------------------------------------------------------------
@AskPayPal Aye

🏢 AmazonHelp
--------------------------------------------------------------------------------
@537378 Hello! This does not appear to be from us. Please do not click any links or enter any information within that ema...

👤 Customer
--------------------------------------------------------------------------------
@537379 @115993 @AmazonHelp could you confirm if this is a official email or not please?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@537379 Hello! I saw that you were in the UK. If so, please forward the fake email to __email__. Sorry for the mistake!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@537378 Sure! Please DM me your PayPal email address and screenshots of your account activity so I can further assess the situation!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@537378 Hey there! For security purposes, please use this reference: to identify suspicious e-mails.


====================================================================================================
CONVERSATION: 1625480
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115830 I just had 18 password assistance code emails in 10 minutes would this be someone trying to access my account?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@182431 You can identify phishing e-mails here: For additional assistance, visit:


====================================================================================================
CONVERSATION: 1245827
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115821 charged me twice on an order. @AmazonHelp

🏢 AmazonHelp
--------------------------------------------------------------------------------
@212613 Oh no! We'd like to take a closer look into these charges. Please contact us via phone or chat:

In [20]:
show_conversation(1937592)
show_conversation(475154)
show_conversation(654356)
show_conversation(2866119)
show_conversation(27884)
show_conversation(622551)

====================================================================================================
CONVERSATION: 1937592
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp My package was supposed to be here on the 9th! The app is telling me that y'all tried to give it to me but I didn't respond?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I've been home the last two days. No one has attempted anything. Not even a note on my door-nothing. Where is my package???

🏢 AmazonHelp
--------------------------------------------------------------------------------
@576395 Oh no! That's not what we want to hear. So we can relay the correct information, could you tell us who the carrier for this delivery was? You can find it here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I got it today! But y'all charged me twice for it?? Once to me, my default card, and once to my roommate. Not my default. I only ordered one

🏢 AmazonHelp
--------------------------------------------------------------------------------
@576395 I'm glad to hear you received your order today! As for the charges are they for the exact same amount? Have they both completed or are is one still pending?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I know they aren't for the same amount, bc I ordered it with other items. I was charged for the full order. My roommate was charged for -

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp only one of the items, although I had already been charged. Mine has gone through, I don't know if his is still pending

🏢 AmazonHelp
--------------------------------------------------------------------------------
@576395 I'm so sorry for the unexpected charge. We'd like to look into this with you. Please reach us here:


====================================================================================================
CONVERSATION: 475154
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115830 you lot are costing ne double money cause if your cacemki g if my order and outting my accoubmnt on hold

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 Hello, without going into personal account info could you tell us more about this please?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I pkaced and order costing auoward of £940 you cancelled the order and out account on hokd due to possabke fraud which it wasnt and niw am getting dispatch emails sent saying ny stuff us being sent when cant get into my account still and was told on ohone 3 times it was cancelled

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 Hi, did you receive an e-mail confirming that the order was canceled?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Yes but i have now recieved 2 dispatch emails for 2 items that were cancelled as i weny a re ordered them thinking they had cancelled it all iff now.am being charged twice and no one is helping ne

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp And niw ive lost the camera i needed cause if tbis you lot have cost ne revenue but doing this bunch of FUCKING COWBOYS get the specialist team to call me now and sort this and refubd ne my money NOW!!!!!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 We'll be happy to look into that for you. Please reach out to us here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I cant even get into my account its been locked out because of possable fraud of an order i placed so i cant even go through that link i was the specialist team to call.me now

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 No worries! Please reach out to us here: Let us know If this helps!

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I want the specialst team who have cause this to call.me now swear to god ill ckaim every last penny back off you lot if this is not sorted you have till 12pm as i said in ohine for this team to call me

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Can reset ny password got email that ibstruct ne to do ao and it wont work

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 I'm sorry for the trouble, please contact us here: You wont be required to sign in to your account in order to contact us using the link I've provided. This will give us an opportunity to take a closer look into what's going on.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Ive done this 6 times i cant do anything

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 When you've contacted us via the link provided, what options/information was provided to you?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp To log in tried to rest password and also to skip login with passcode neither work

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp A just need acces to my account why are you lot making this so hard for me

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 We aren't able to access your account via Twitter to see what the exact issue is, but normally you should be sent an e-mail requesting either payment or address verification. Have you received an e-mail like this, or was this mentioned when we spoke on the phone?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Yes abd it said that aftwr 5 hours from yesterday i can rest password and re verify all details but it wont allow me to access the account to sort this

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 We would like to take a closer look into this for you, please click on the following link and my team will be in touch as soon as they can.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Tried you link this is what i get why is this soo hard to fix

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 I'm sorry for the inconvenience! We don't have access to your account via Twitter. Please reach out to us here so we can assist you better:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Ive already sent a notice to get ny password reset 10.minutes ago a need this done now or what ever fucking restriction there is in place removed so i can get back on

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Have regained access to ny account but you still have a hold on it why

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 I would advise to log out from any and all devices connected to your account and then log in again to see if this helps.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp But why am i gwletting emails for items that are not on the order or cancelation list ???

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 To clarify, are you receiving e-mails for items that have been dispatched that you didn't order? Your account security is important to us, so please let us know.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I am getting them for items i ordered that you lot cancelled off

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 Emails sent from Amazon can't be viewed in Twitter. Please allow one of the members of our team to assist you directly by phone here: - SE

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp No cause my account is still on hold

🏢 AmazonHelp
--------------------------------------------------------------------------------
@228071 When you select this link, do you see an option to "skip sign in": If you do not see this option, please try using a device with a full web browser, like a PC, mac, or notebook.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Again i tried to order my camera and it was cancelled fuck you amazing im taking my buisness else where FUCKING CUNTS YOU LOT


====================================================================================================
CONVERSATION: 654356
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
I’ve been ripped off so much by @115830 I’ve been charged twice (£78 total) for a game. What is my life

👤 Customer
--------------------------------------------------------------------------------
@115830 @AmazonHelp

🏢 AmazonHelp
--------------------------------------------------------------------------------
@275657 Hi. Thanks for reaching out today! I'm terribly sorry to hear about the problem you've had with Prime. Please reach out to us here: so we can look at available options.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@275657 I'm sorry for the trouble. We're here to help! Please call or chat in so we can look at available resolution options here: Keep us updated how that goes.


====================================================================================================
CONVERSATION: 2866119
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Hey! So I was being charged for Prime on and Amazon.ca simultaneously. Turns out I paid for multiple months on both, how do I get refunded for those months?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@796055 We'd love to help! For the Prime membership on you may reach us here: For the Prime membership on Amazon.ca you may reach us here: .


====================================================================================================
CONVERSATION: 27884
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115821 have taken £80 out my account without my consent

🏢 AmazonHelp
--------------------------------------------------------------------------------
@122102 This could be a Prime charge that you can cancel through your account

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp But I haven’t even consented to prime before I want my money back

🏢 AmazonHelp
--------------------------------------------------------------------------------
@122102 I know this can be frustrating. After you have canceled the membership, it will automatically process a refund.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Really? Right ok how long for a refund

🏢 AmazonHelp
--------------------------------------------------------------------------------
@122102 In most cases, refunds can take 5-7 business days. You can find more info here:


====================================================================================================
CONVERSATION: 622551
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
When you come home to an absolutely sodden, ruined parcel. I’m actually fuming @AmazonHelp

🏢 AmazonHelp
--------------------------------------------------------------------------------
@267760 I'm terribly sorry for the condition of your parcel, Kelly! We can look into the available refund/replace options and leave carrier feedback for you here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp How can I return it-I have nothing to return it in? The box is so wet it is crumbling in my hand! I am not prepared to pay to return it when it wasn’t my fault, but incompetent delivery men!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@267760 I'm very sorry for the frustration, Kelly! I completely understand your concern. We'd like to help! When reaching out to us what options were provided to you?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Refund or replace-if I send the old one back.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Is anyone going to reply to me, and give me any more options? I would like a refund due to incompetent delivery drivers. What is the point of prime when idiots leave paper based items packaged in cardboard in torrential rain?!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@267760 I'm sorry for the delayed response, Kelly. Please contact us by phone or chat using the link provided and we'll be happy to look into all available resolution options for you! We want to help!

In [19]:
show_conversation(73460)
show_conversation(956288)
show_conversation(693)
show_conversation(224617)
show_conversation(2667982)
show_conversation(2534495)

====================================================================================================
CONVERSATION: 73460
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
This is what i received, broken car steering mobile holder from @115821 @AmazonHelp @115850 Order id : 402-4901639-7214711. This was unexpected from such a big brand

🏢 AmazonHelp
--------------------------------------------------------------------------------
@132428 Sorry to know you've received a faulty product, Prem. You can create a return request here: Also, please don't provide your order details, we consider it to be personal information. Our page is visible to the public.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp This is what it saying. I just want to replace it.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@132428 As per the screenshot, the item in picture isn't eligible for return. You can refer to our return policies here : Appreciate your understanding here.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I just want to return this, pls raise my concern. Not able to do this from my end. Dont expect anything from my end. If this not done then i will make sure will not buy anymore from @115850

🏢 AmazonHelp
--------------------------------------------------------------------------------
@132428 We understand your concern regarding the return of your order. Kindly connect with our support team here: and we'll assist you accordingly.


====================================================================================================
CONVERSATION: 956288
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Is PRime charge for each country yu use? IE Im in canada and wanted to order something from US Amazon

🏢 AmazonHelp
--------------------------------------------------------------------------------
@346904 1/2 No, it's only for the country it was purchased for. Your .ca Prime won't work on Amazon .com. You can still order from

🏢 AmazonHelp
--------------------------------------------------------------------------------
@346904 2/2 from Amazon .com but the Prime benefits won't be available. I hope this helps!


====================================================================================================
CONVERSATION: 693
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp since when you stop giving 20% off videogame pre-orders (amazon prime members) im confused? why?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@115852 We still offer discounts on eligible physical game pre-orders. For further details on Prime benefits:


====================================================================================================
CONVERSATION: 224617
====================================================================================================

🏢 AmazonHelp
--------------------------------------------------------------------------------
@169665 I'm sorry, I'm unable to comprehend. Could you please be more specific?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Team as u can see the product has the price of 5200 and next to it is the delivery price of 3000 Rs. Which product has this much delivery ??

🏢 AmazonHelp
--------------------------------------------------------------------------------
@169665 Thank you for elaborating your concern. For the seller fulfilled items, Sellers determine their own shipping charges 1/3

🏢 AmazonHelp
--------------------------------------------------------------------------------
@169665 for different shipping speeds. You can find seller shipping charges on the seller's profile page which is 2/3

🏢 AmazonHelp
--------------------------------------------------------------------------------
@169665 accessible by clicking the seller's name on the product details page. 3/3


====================================================================================================
CONVERSATION: 2667982
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115850 so flipkart cheaper then you?

🏢 AmazonHelp
--------------------------------------------------------------------------------
@751543 However, you can always let us know about a lower price by clicking the "tell us about a lower price" link in the Product Details section of any product page. 2/2

🏢 AmazonHelp
--------------------------------------------------------------------------------
@751543 The constantly changing marketplace and our efforts to offer you the lowest price, may result in fluctuations in our prices over time. 1/2


====================================================================================================
CONVERSATION: 2534495
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115830 my husband has had his account hacked & completely blocked him out.Emailed Amazon & they said they have took control of his account & to change password but with no joy.Is there a uk phone number to contact Amazon to sort this out?Can’t do anything as need to log in. Ta

🏢 AmazonHelp
--------------------------------------------------------------------------------
@721140 Hi Ema- Can you ask your husband to contact us via this link: he won't be required to sign in. Thanks.

In [18]:
show_conversation(2909256)
show_conversation(1406110)
show_conversation(138143)
show_conversation(977763)
show_conversation(2212072)

====================================================================================================
CONVERSATION: 2909256
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp My account was hacked. Someone changed the email address associated w/ my account & I cannot access my account. I am a Prime member, have both Prime credit cards & use streaming services. I’ve called customer service 3 times since 11/17. Still can’t access account.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@805454 I'm so sorry for the ongoing trouble with your account, Travis! I'd like to have a member of our team look into this on your behalf. Please "skip sign in" and send us the details here:

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Thank you thank you thank you thank you!! I just submitted the info and I really appreciate your help! I just want to log into my account, use prime services, stream video, etc.!!!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@805454 You're very welcome, Travis!

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp HELP ME!!!!! ‍️


====================================================================================================
CONVERSATION: 1406110
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115821 bug payment failed from credit card add money to amazon pay and try to complete order by amazon pay no option.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@446839 I'm sorry for the trouble you're facing with the payment. Kindly reach out to our support team here: we'll look into it and help you out.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp They tried eventually i had ro ask for order cancellation. i raised it as seems to me as bug/ or enhancement needed, so reported to fix it.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@446839 Thank you very much for keeping us updated. Our team will definitely work on fixing it.


====================================================================================================
CONVERSATION: 138143
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@115830 Just had the worst experience with your customer service team, spoke to two different people and the second had no clue what was going on, didn't understand half of what I was saying and couldn't answer any questions or even look up the correct order. #frustrating

🏢 AmazonHelp
--------------------------------------------------------------------------------
@147116 I'm sorry to hear this. Without divulging any personal information, could you explain the issue that you were having?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Basically I ordered 3 items as gifts for my girlfriend so I can't say what they are. The money was taken from my account for 2 of the items, but I received an email saying the payment was declined. Part 1...

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Talked to the bank they said everything was approved on their end. They released the money back to my account, so I called customer care to make sure everything was ok before I attempted payment again and was met with much confusion and left very frustrated. Part 2...

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Long story short the woman seemed like she had no idea what was happening. Addressed none of the issues I had, apologised numerous times for her confusion, left me very annoyed which ended with me having no idea what was going on and ending the call. Part 3.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@147116 Very sorry to hear that. Have we been able to ensure the gifts have processed for you? Have we confirmed the payment has gone through ? We certainly would like to help if possible.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I think she updated the payment, but when I asked when it would be charged to my account as nothing appears to have been charged yet, she proceeded to give me delivery date information.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@147116 Really sorry about this. I'm afraid we don't have access to account details here on Twitter.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp That's ok. Just had to vent about the issue. Everything looks ok on the account from what I can see. I'll keep an eye and if I have any issues I shall contact support again. Thanks!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@147116 No worries at all :) Let us know if you need anything else!


====================================================================================================
CONVERSATION: 977763
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @115830 why does it have to be so difficult and such a painful process trying to get a resolution? #drivingmemad

🏢 AmazonHelp
--------------------------------------------------------------------------------
@351898 Sorry to hear this. Without sharing personal/account info, can you please advise what happened ?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Just cannot seem to resolve an issue with a return - 5 days, 12+ calls and probably 6 hours on phone later still don’t think fixed

🏢 AmazonHelp
--------------------------------------------------------------------------------
@351898 What exactly is the issue? Are you able to elaborate? What did customer service advise?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Too difficult for telephone it seems so Twitter will be a challenge - just want someone who can actually fix it to call me from the UK

🏢 AmazonHelp
--------------------------------------------------------------------------------
@351898 Apologies - what ti s the return issue ? What info have we supplied ?

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp My twitter name is my account name so look it up. I cannot go through this on Twitter - there is too much information.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp All I want is for a UK based manager to call me to resolve this issue.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@351898 We can't access your account from here. Please get in touch and we'll be happy to help:

🏢 AmazonHelp
--------------------------------------------------------------------------------
@351898 we don't have access to your account here but click here: we'll help.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Great, another non UK call centre, thanks for that, another wasted phone call.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp #nothelpful

🏢 AmazonHelp
--------------------------------------------------------------------------------
@351898 We have different call centres all over the world Matthew.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Really, I never guessed that one. Sadly you are kind of missing the point though. I would like to speak with a manager in the UK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp So once again fallen at the first hurdle

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp And I still haven’t had a call I was promised by Cust Serv - should only be a few hours - 36 later, still nothing!


====================================================================================================
CONVERSATION: 2212072
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Paid through Amazon Pay. Received Delivery message even though product wasn't delivered. Wtf!

🏢 AmazonHelp
--------------------------------------------------------------------------------
@646523 Our apologies! Missing orders can be found by following the steps mentioned here: If it doesn't help, please reach out t us here: from the order related account and we'll check this.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp The product was delivered next door. Have collected from them. Pls close the complaint.

🏢 AmazonHelp
--------------------------------------------------------------------------------
@646523 Glad to hear you got the package. Do keep us posted for any further assistance.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @646523 See this again a fake promise from amazon i got this mail yesterday amazon is a cheater website and giving fake promises everytime ! Again the said self return for my pakages but i already send my package 4time to amazon fullfillment centre but they refused to take it there .

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @646523 Eventhey didnt paid me my currier charges 2200,2100,143,2200 rs

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp @646523 This amazon website is making fool to indians !

🏢 AmazonHelp
--------------------------------------------------------------------------------
@635876 Sorry to know about the return issue. Please reply to the email you've received from our Social media team and we'll reach out to you. Also, please don't provide your order details, we consider it to be personal information. Our page is visible to the public.

In [39]:
show_conversation(17216)
show_conversation(216059)
show_conversation(487843)
show_conversation(996702)
show_conversation(1038870)
show_conversation(2850744)

====================================================================================================
CONVERSATION: 17216
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] what is the use of Prime Membership if I am not getting my parcel on time.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We're sorry for the delay in the delivery of your order. Please contact us here: and we'll help you ^ZH

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Pathetic reply by your caller

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Did we happen to miss the estimated delivery date? ^AG

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp No use of prime membership, return my money

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Could you please confirm, if we've missed the estimated delivery date? ^AG

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp After prime membership gaurantied delivery option has vanished now

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] The guaranteed delivery date will be available based on various factors such as location, courier used, distance etc.(1/2) ^ZH

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] If the factors do not provide the feasibility of a guaranteed delivery, the option will not be available. (2/2) ^ZH

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp When i was not a member everything was under gaurantied delivery and once i paid for membership facility is limited

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We will consider this as feedback and ensure to pass it on internally for improvements. ^RW

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Kindly return my prime membership amount

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please connect with our support team here: for further assistance on it. ^RW

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Kindly share my contact number 9800019281 to ur team to contact me

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We're unable to arrange a callback for you over Twitter. Please make a request using the link above and we'll oblige. 1/2 ^AB

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Also, please don't provide your contact details as its personal info. Our Twitter page is visible to public. 2/2 ^AB

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp See after getting amount it happens that eveyone become unable in assisting.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Twitter being a public platform we do not have access to your order details. (1/2) ^SI

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Due to which we do not have an option to call you back, please use the link provided earlier to request a call back. (2/2) ^SI

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Thats why i writing here that rest of the people shd know about your services and how you r making fool on name of prime

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Sorry for the disappointment. As mentioned earlier, please reach out to us using the link provided earlier for (1/2) ^KA

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] further assistance. Appreciate your understanding. (2/2) ^KA

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I dont need to contact u now, it is as mistake take that i paid for Prime.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I get your disappointment. However, we'll not be able to contact you over Twitter. Kindly reach (1/2) ^GK

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] out to our team using the link shared earlier. (2/2) ^GK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I will not contact ur supoort team.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Kindly note i will not received or accept my last order. I have choosen COD but due bad service of Prime i will not accept

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry for the unpleasant experience. We'd like to change it. Please (1/2)^SF

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] provide your details here: &amp; we'll get this sorted.(2/2)^SF

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp I dont want to change my order but will not accept. Order # 403-3917499-2913904

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We'd like to assist you with the issue, kindly provide your details through the link provided above and we'll get back 1/2 ^SH

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] to you. Please don’t provide your details as we consider them to be personal information. Our Twitter page is public. 2/2 ^SH


====================================================================================================
CONVERSATION: 216059
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Why are the prices for my subscriptions different in the email than on my subscription page? It’s more than a 10€ difference! What price will I be charged?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Hello Shannon, can you please tell us which subscription page are you talking about? ^SA

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp The one where I can see all my subscriptions and when they’ll be mailed. I can also modify the subscriptions and cancel them. Even on the product page, the price is cheaper than in the email I received.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp In English it may be called something different. In French, it’s “gérer vos abonnements”.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Could you please explain more ? Is it concerning your Prime membership ? ^SM

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Pampers Premium Taille 3 diapers are 31.94€ on manage subscription page (and product page) and 43.33€ in email I received. What price will I be charged?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] When you sign up for a subscription your percentage discount is guaranteed. This discount is calculated based on the price of the product the day it is billed and sent to you. ^MD

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp So the price is going to go up by the time it is sent to me? Today is the last day I can modify my order.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please reach our CS using this link in order to check with them.^FT


====================================================================================================
CONVERSATION: 487843
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
[USER] still hasn’t refunded me my money for the unauthorized charges that was made to my account

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I'm sorry for the unexpected charge to your account. We don't have access to account information via Twitter, please reach out to us here: ^MH


====================================================================================================
CONVERSATION: 996702
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
I am deeply disturbed and annoyed with [USER] they basically cancelled and order that I had already paid and refuse to give me my money.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Sorry for the inconvenience! Has the order shipped? We will only charge for an order if it ships out successfully. ^JE

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp It's not shipped but is charged. I can assure you this. I have this in an email from your company. Talked to a lot of Amazon employees.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp The only thing they know how to do Is cancel my account. That they do it perfectly.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Although we don't charge until the order ships, we do hold an authorization charge to be sure the money will be available(1/2)

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] when it does ship. You can learn more about how to remove those here: ^HC (2/2)

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp That's not what I was told

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Read email above. The cell phone never shipped. And now I have to pay more money for it because it costs more and I need a speed shipment.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp And it was time consuming calling Amazon and getting nothing good for it

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] The cell phone never shipped because it was reported as an unauthorized charge. The order would have been canceled. 1/2 ^ZW

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] We recommend that you dispute the charge with your bank and also cancel the credit card. 2/2 ^ZW

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp You have only one response and is this. The orders cancelled where my orders. I shouldn't be bother to talk to the bank when you messed up.


====================================================================================================
CONVERSATION: 1038870
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp sbi card offer valid on Amazon pay purchase?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] I get your concern, Nappa. This offer is not valid on purchase of Gift Card(s) (Amazon branded and Non Amazon branded). (1/2) ^SV

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Please refer here: for more info. (2/2) ^SV

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp What if I add money on my amazon pay via sbi card?

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] As mentioned earlier, it is not applicable on Gift Card(s) (Amazon branded and Non Amazon branded). Amazon pay balance is 1/2 ^NK

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Amazon gift card which is not eligible for this offer. Request you to make a note of it. 2/2 ^NK

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp OK thanks.

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] You're welcome. Do keep us posted for any further assistance. ^SV


====================================================================================================
CONVERSATION: 2850744
====================================================================================================

👤 Customer
--------------------------------------------------------------------------------
Why? @AmazonHelp

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thank you for bringing this to our attention; could you provide us with the link to this promotional code you're trying to use? We'd like to review this on your behalf. ^WM

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Thanks. It's on the website...

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Is this working yet? Thanks

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] The promotion is working here for me when I select it. Can you confirm that all the items in your order qualify for the promotion? You can find information on the terms towards the bottom of this page: ^MI

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp Yes, all Amazon Pantry items and subtotal is £35.93. Just tried it again but getting the same error message.

👤 Customer
--------------------------------------------------------------------------------
@AmazonHelp It's okay - just realised wine isn't included

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] It appears that you've included chardonnay in your order. Wine and spirits are not eligible for this offer. ^RA

🏢 AmazonHelp
--------------------------------------------------------------------------------
[USER] Thank you for the update! Please let us know if you have further questions or concerns. We're here to help! ^TG